// Generated by easyread/scripts/visual-living.mjs. Do not edit; edit the client's copy.
/**
 * Drawings the library was missing, drawn for it and kept by hand.
 *
 * Written by easyread-server/scripts/visual-accept.ts. Every entry in
 * here was asked for by a real page, drawn from a description with its
 * name withheld, put through the gate and the judge, and then looked
 * at by a person who said keep it. Edit it like any other pack; the
 * script only ever adds.
 */
import type { Preset } from "../presets";

export const DRAWN: Record<string, Preset> = {};
