// Generated by easyread/scripts/visual-living.mjs. Do not edit; edit the client's copy.
/**
 * Drawings the library was missing, drawn for it and kept by hand.
 *
 * Written by easyread-server/scripts/visual-accept.ts. Every entry in
 * here was asked for by a real page, drawn from a description with its
 * name withheld, put through the gate and the judge, and then looked
 * at by a person who said keep it. Edit it like any other pack; the
 * script only ever adds.
 */
import type { Preset } from "../presets";

export const DRAWN: Record<string, Preset> = {
  "page": {
    svg: "<svg viewBox=\"-4.00 -4.00 808.00 608.00\" xmlns=\"http://www.w3.org/2000/svg\">\n  <g id=\"background\">\n    <rect width=\"800\" height=\"600\" fill=\"#f0f0f0\"/>\n  </g>\n  <g id=\"rectangular_shape\">\n    <rect x=\"50\" y=\"50\" width=\"700\" height=\"500\" fill=\"#ffffff\" stroke=\"#cccccc\" stroke-width=\"5\"/>\n  </g>\n  <g id=\"top_left_corner\">\n    <rect x=\"50\" y=\"50\" width=\"350\" height=\"200\" fill=\"#e0e0e0\" stroke=\"#aaaaaa\" stroke-width=\"3\"/>\n  </g>\n  <g id=\"top_right_corner\">\n    <rect x=\"400\" y=\"50\" width=\"350\" height=\"200\" fill=\"#e0e0e0\" stroke=\"#aaaaaa\" stroke-width=\"3\"/>\n  </g>\n  <g id=\"bottom_left_corner\">\n    <rect x=\"50\" y=\"300\" width=\"350\" height=\"200\" fill=\"#e0e0e0\" stroke=\"#aaaaaa\" stroke-width=\"3\"/>\n  </g>\n  <g id=\"bottom_right_corner\">\n    <rect x=\"400\" y=\"300\" width=\"350\" height=\"200\" fill=\"#e0e0e0\" stroke=\"#aaaaaa\" stroke-width=\"3\"/>\n  </g>\n</svg>",
    aspect: 1.33,
    tags: "page",
    outline: true,
    parts: {
      "background": { at: [400, 300] },
      "rectangular_shape": { at: [400, 300] },
      "top_left_corner": { at: [225, 150] },
      "top_right_corner": { at: [575, 150] },
      "bottom_left_corner": { at: [225, 400] },
      "bottom_right_corner": { at: [575, 400] },
    },
  },
  "rules": {
    svg: "<svg viewBox=\"296.00 176.00 208.00 328.00\">\n  <g id=\"cylinder\">\n    <ellipse cx=\"400\" cy=\"450\" rx=\"100\" ry=\"20\" fill=\"#ccc\" />\n    <rect x=\"300\" y=\"200\" width=\"200\" height=\"300\" fill=\"#aaa\" />\n    <ellipse cx=\"400\" cy=\"200\" rx=\"100\" ry=\"20\" fill=\"#ccc\" />\n  </g>\n  <g id=\"lid\">\n    <ellipse cx=\"400\" cy=\"200\" rx=\"100\" ry=\"20\" fill=\"#999\" />\n  </g>\n  <g id=\"rules\">\n    <rect x=\"320\" y=\"220\" width=\"160\" height=\"260\" fill=\"#fff\" stroke=\"#000\" stroke-width=\"2\" />\n    <line x1=\"320\" y1=\"260\" x2=\"480\" y2=\"260\" stroke=\"#000\" stroke-width=\"2\" />\n    <line x1=\"320\" y1=\"300\" x2=\"480\" y2=\"300\" stroke=\"#000\" stroke-width=\"2\" />\n    <line x1=\"320\" y1=\"340\" x2=\"480\" y2=\"340\" stroke=\"#000\" stroke-width=\"2\" />\n    <line x1=\"320\" y1=\"380\" x2=\"480\" y2=\"380\" stroke=\"#000\" stroke-width=\"2\" />\n    <line x1=\"320\" y1=\"420\" x2=\"480\" y2=\"420\" stroke=\"#000\" stroke-width=\"2\" />\n    <line x1=\"320\" y1=\"460\" x2=\"480\" y2=\"460\" stroke=\"#000\" stroke-width=\"2\" />\n  </g>\n</svg>",
    aspect: 0.63,
    tags: "rules",
    outline: true,
    parts: {
      "cylinder": { at: [400, 340] },
      "lid": { at: [400, 200] },
      "rules": { at: [400, 350] },
    },
  },
  "voice": {
    svg: "<svg viewBox=\"-34.00 -54.00 838.00 658.00\">\n  <g id=\"outer_frame\">\n    <rect width=\"800\" height=\"600\" fill=\"#e0f7fa\"/>\n  </g>\n  <g id=\"microphone_body\" transform=\"translate(350, 200)\">\n    <ellipse cx=\"0\" cy=\"0\" rx=\"30\" ry=\"50\" fill=\"#616161\"/>\n    <rect x=\"-10\" y=\"0\" width=\"20\" height=\"100\" fill=\"#424242\"/>\n  </g>\n  <g id=\"sound_wave\" transform=\"translate(340, 160)\">\n    <path d=\"M0,0 Q20,-20 40,0 T80,0 T120,0 T160,0 T200,0\" fill=\"none\" stroke=\"#ffab00\" stroke-width=\"3\"/>\n  </g>\n  <g id=\"sound_wave_reflection\" transform=\"translate(340, 160)\">\n    <path d=\"M0,0 Q20,20 40,0 T80,0 T120,0 T160,0 T200,0\" fill=\"none\" stroke=\"#ffab00\" stroke-width=\"3\" stroke-opacity=\"0.5\"/>\n  </g>\n</svg>",
    aspect: 1.27,
    tags: "voice",
    outline: true,
    parts: {
      "outer_frame": { at: [400, 300] },
      "microphone_body": { at: [0, 25] },
      "sound_wave": { at: [100, -10] },
      "sound_wave_reflection": { at: [100, 10] },
    },
  },
};
