// Generated by easyread/scripts/visual-living.mjs. Do not edit; edit the client's copy.
/**
 * Living things with a body plan: an insect, a fish, a bird, an animal
 * on four legs, a segmented crawler, a person. Each is a small skeleton
 * of ellipses and strokes with named parts, so a page's tsetse fly has
 * wings that beat and a proboscis a callout can point at.
 */
import {
  closed,
  ellipse,
  pt,
  rnd,
  type FigureOp,
  type FigureRole,
  type Frame,
} from './figures-ops';

type P = [number, number];
type Anchors = Record<string, P>;

const polar = (a: P, angle: number, r: number): P => [
  a[0] + Math.cos(angle) * r,
  a[1] + Math.sin(angle) * r,
];
const poly = (points: P[]) =>
  `M ${pt(points[0])} ${points
    .slice(1)
    .map((p) => `L ${pt(p)}`)
    .join(' ')}`;
const curve = (a: P, c: P, b: P) => `M ${pt(a)} Q ${pt(c)} ${pt(b)}`;
const dot = (ops: FigureOp[], p: P, r: number, fill: FigureRole, alpha = 1) =>
  ops.push({ kind: 'dots', points: [p], r, fill, alpha });

/** Bands across a body, drawn dark and soft. */
function stripes(
  ops: FigureOp[],
  cx: number,
  cy: number,
  rx: number,
  ry: number,
  count: number,
  from = -0.5,
  to = 0.6,
): void {
  let d = '';
  for (let i = 0; i < count; i += 1) {
    const u = from + ((to - from) * (i + 0.5)) / count;
    const x = cx + u * rx;
    const half = ry * Math.sqrt(Math.max(0, 1 - u * u)) * 0.92;
    d += ` M ${x.toFixed(2)} ${(cy - half).toFixed(2)} L ${x.toFixed(2)} ${(cy + half).toFixed(2)}`;
  }
  ops.push({
    kind: 'path',
    d: d.trim(),
    stroke: 'ink',
    width: 2.4,
    alpha: 0.45,
  });
}

/** Spots over a body. */
function spots(
  ops: FigureOp[],
  cx: number,
  cy: number,
  rx: number,
  ry: number,
  seed: number,
  count = 6,
): void {
  const points: P[] = [];
  for (let i = 0; i < count; i += 1) {
    const a = rnd(seed, i + 50) * Math.PI * 2;
    const k = 0.25 + 0.5 * rnd(seed, i + 70);
    points.push([cx + Math.cos(a) * rx * k, cy + Math.sin(a) * ry * k]);
  }
  ops.push({
    kind: 'dots',
    points,
    r: Math.max(1.4, Math.min(rx, ry) * 0.12),
    fill: 'ink',
    alpha: 0.4,
  });
}

/* ── insect: head, thorax, abdomen, on legs, with wings ─────────────── */

export function insectFigure(
  f: Frame,
  ops: FigureOp[],
  anchors: Anchors,
): void {
  const { cx, cy, rx, ry, t, seed, parts, manner } = f;
  const flying = manner === 'flutter' || manner === 'fly' || manner === 'hover';
  const walking = manner === 'walk' || manner === 'crawl';
  const y0 = cy + (flying ? Math.sin(t * 3.1 + seed) * ry * 0.06 : 0);
  const headX = cx + rx * 0.6;
  const thoraxX = cx + rx * 0.2;
  const abdX = cx - rx * 0.32;
  const headR = Math.min(rx * 0.14, ry * 0.2);
  const thoraxRx = rx * 0.2;
  const thoraxRy = ry * 0.26;
  const abdRx = rx * 0.4;
  const abdRy = ry * 0.3;
  // Legs first, so the body sits over their roots.
  if (parts.has('legs')) {
    let d = '';
    for (const side of [-1, 1]) {
      for (let k = 0; k < 3; k += 1) {
        const base: P = [
          thoraxX + (k - 1) * thoraxRx * 0.6,
          y0 + side * thoraxRy * 0.55,
        ];
        const fan = (k - 1) * 0.5;
        const swing = walking
          ? Math.sin(t * 7 + (k + (side > 0 ? 1 : 0)) * Math.PI) * 0.32
          : flying
            ? 0.25
            : 0;
        const a = side * (Math.PI / 2) - fan * side * 0.9 + swing;
        const knee = polar(base, a, rx * 0.2);
        const foot = polar(knee, a + side * 0.95 + fan * 0.3, rx * 0.2);
        d += ` ${poly([base, knee, foot])}`;
        if (side === 1 && k === 1) anchors.legs = foot;
      }
    }
    ops.push({
      kind: 'path',
      d: d.trim(),
      stroke: 'edge',
      width: 1.5,
      alpha: 0.95,
    });
  }
  if (parts.has('wings')) {
    const root: P = [thoraxX, y0];
    const length = rx * 0.66;
    const width = ry * 0.2;
    const wing = (angle: number, alpha: number, side: number) => {
      const centre = polar(root, angle, length / 2);
      ops.push({
        kind: 'path',
        d: ellipse(centre[0], centre[1], length / 2, width / 2, angle),
        fill: 'body',
        fillAlpha: 0.3 * alpha,
        stroke: 'edge',
        width: 1,
        alpha: 0.7 * alpha,
      });
      if (side < 0 && alpha === 1) anchors.wings = polar(root, angle, length);
    };
    for (const side of [-1, 1]) {
      const spread = Math.PI - side * 1.05;
      if (manner === 'flutter' || manner === 'hover') {
        // Three beats at once, faint, the way a wing looks when it is too fast to see.
        for (const [delta, alpha] of [
          [-0.4, 0.45],
          [0, 1],
          [0.4, 0.45],
        ] as const)
          wing(spread + side * (delta + Math.sin(t * 40) * 0.08), alpha, side);
      } else if (manner === 'fly') {
        wing(spread + side * Math.sin(t * 2.6) * 0.55, 1, side);
      } else {
        // Folded flat over the back.
        wing(Math.PI + side * 0.14, 1, side);
      }
    }
  }
  // Abdomen, thorax, head.
  ops.push({
    kind: 'path',
    d: ellipse(abdX, y0, abdRx, abdRy),
    fill: 'body',
    fillAlpha: 0.92,
    stroke: 'edge',
    width: 1.6,
  });
  if (parts.has('stripes'))
    stripes(ops, abdX, y0, abdRx, abdRy, 3, -0.55, 0.65);
  if (parts.has('spots')) spots(ops, abdX, y0, abdRx, abdRy, seed, 5);
  if (parts.has('stinger')) {
    const tip: P = [abdX - abdRx * 1.25, y0 + abdRy * 0.1];
    ops.push({
      kind: 'path',
      d: `${poly([[abdX - abdRx * 0.95, y0 - abdRy * 0.25], tip, [abdX - abdRx * 0.95, y0 + abdRy * 0.3]])} Z`,
      fill: 'ink',
      fillAlpha: 0.8,
    });
    anchors.stinger = tip;
  }
  ops.push({
    kind: 'path',
    d: ellipse(thoraxX, y0, thoraxRx, thoraxRy),
    fill: 'body',
    fillAlpha: 1,
    stroke: 'edge',
    width: 1.6,
  });
  ops.push({
    kind: 'path',
    d: ellipse(headX, y0, headR, headR * 1.05),
    fill: 'body',
    fillAlpha: 1,
    stroke: 'edge',
    width: 1.6,
  });
  const eye: P = [headX + headR * 0.3, y0 - headR * 0.5];
  dot(ops, eye, headR * 0.32, 'ink', 0.9);
  dot(ops, [headX + headR * 0.3, y0 + headR * 0.5], headR * 0.32, 'ink', 0.9);
  if (parts.has('antennae')) {
    const wave = Math.sin(t * 2.1) * 0.12;
    let d = '';
    for (const side of [-1, 1]) {
      const from: P = [headX + headR * 0.6, y0 + side * headR * 0.45];
      const tip: P = [headX + headR * 2.3, y0 + side * headR * (1.7 + wave)];
      d += ` ${curve(from, [headX + headR * 1.9, y0 + side * headR * 0.5], tip)}`;
      if (side < 0) anchors.antennae = tip;
    }
    ops.push({
      kind: 'path',
      d: d.trim(),
      stroke: 'edge',
      width: 1.2,
      alpha: 0.9,
    });
  }
  if (parts.has('proboscis')) {
    const from: P = [headX + headR * 0.85, y0 + headR * 0.25];
    const tip: P = [headX + headR * 2.7, y0 + headR * 1.05];
    ops.push({
      kind: 'path',
      d: poly([from, tip]),
      stroke: 'ink',
      width: 1.7,
      alpha: 0.9,
    });
    anchors.proboscis = tip;
  }
  anchors.head = [headX, y0];
  anchors.thorax = [thoraxX, y0];
  anchors.abdomen = [abdX, y0];
  anchors.eye = eye;
  anchors.edge = [abdX - abdRx, y0];
}

/* ── fish: a body that sweeps its tail ─────────────────────────────── */

export function fishFigure(f: Frame, ops: FigureOp[], anchors: Anchors): void {
  const { cx, cy, rx, ry, t, seed, parts, manner } = f;
  const swimming = manner !== 'still';
  const wag = swimming ? Math.sin(t * 3.4 + seed) : 0;
  const bendAt = (x: number) =>
    x < cx ? wag * ((cx - x) / rx) * ry * 0.14 : 0;
  const body: P[] = [];
  for (let i = 0; i < 40; i += 1) {
    const th = (i / 40) * Math.PI * 2;
    const x = cx + rx * 0.18 + Math.cos(th) * rx * 0.72;
    const thin = 0.55 + 0.45 * ((Math.cos(th) + 1) / 2);
    body.push([x, cy + Math.sin(th) * ry * 0.5 * thin + bendAt(x)]);
  }
  const tailRoot: P = [cx - rx * 0.5, cy + bendAt(cx - rx * 0.5)];
  const tailTop: P = [cx - rx * 0.97, cy - ry * 0.55 + wag * ry * 0.22];
  const tailBottom: P = [cx - rx * 0.97, cy + ry * 0.55 + wag * ry * 0.22];
  ops.push({
    kind: 'path',
    d: `${poly([tailRoot, tailTop, [cx - rx * 0.82, cy + wag * ry * 0.2], tailBottom])} Z`,
    fill: 'body',
    fillAlpha: 0.7,
    stroke: 'edge',
    width: 1.4,
  });
  if (parts.has('fins')) {
    const top = cy - ry * 0.45;
    ops.push({
      kind: 'path',
      d: `${poly([
        [cx - rx * 0.25, top + ry * 0.05],
        [cx + rx * 0.02, cy - ry * 0.95],
        [cx + rx * 0.28, top],
      ])} Z`,
      fill: 'body',
      fillAlpha: 0.6,
      stroke: 'edge',
      width: 1.2,
    });
    const flap = swimming ? Math.sin(t * 4 + 1) * ry * 0.06 : 0;
    ops.push({
      kind: 'path',
      d: `${poly([
        [cx + rx * 0.3, cy + ry * 0.12],
        [cx + rx * 0.05, cy + ry * 0.5 + flap],
        [cx + rx * 0.35, cy + ry * 0.3],
      ])} Z`,
      fill: 'body',
      fillAlpha: 0.75,
      stroke: 'edge',
      width: 1.2,
    });
    anchors.fins = [cx + rx * 0.02, cy - ry * 0.9];
  }
  ops.push({
    kind: 'path',
    d: closed(body),
    fill: 'body',
    fillAlpha: 0.92,
    stroke: 'edge',
    width: 1.8,
  });
  if (parts.has('stripes'))
    stripes(ops, cx + rx * 0.18, cy, rx * 0.72, ry * 0.5, 4, -0.5, 0.45);
  if (parts.has('spots'))
    spots(ops, cx + rx * 0.15, cy, rx * 0.6, ry * 0.4, seed, 6);
  // A gill line and the eye.
  ops.push({
    kind: 'path',
    d: curve(
      [cx + rx * 0.5, cy - ry * 0.32],
      [cx + rx * 0.42, cy],
      [cx + rx * 0.5, cy + ry * 0.32],
    ),
    stroke: 'edge',
    width: 1.2,
    alpha: 0.7,
  });
  const eye: P = [cx + rx * 0.68, cy - ry * 0.12];
  dot(ops, eye, Math.max(1.6, Math.min(rx, ry) * 0.08), 'ink', 0.9);
  ops.push({
    kind: 'path',
    d: poly([
      [cx + rx * 0.9, cy + ry * 0.06],
      [cx + rx * 0.8, cy + ry * 0.14],
    ]),
    stroke: 'ink',
    width: 1.3,
    alpha: 0.7,
  });
  anchors.head = [cx + rx * 0.66, cy];
  anchors.body = [cx + rx * 0.1, cy];
  anchors.tail = tailTop;
  anchors.eye = eye;
  anchors.edge = [cx + rx * 0.18, cy - ry * 0.5];
}

/* ── bird: a body with wings, a beak and a tail ───────────────────── */

export function birdFigure(f: Frame, ops: FigureOp[], anchors: Anchors): void {
  const { cx, cy, rx, ry, t, seed, parts, manner } = f;
  const flying = manner === 'fly' || manner === 'hover' || manner === 'flutter';
  const walking = manner === 'walk';
  const y0 = cy + (flying ? Math.sin(t * 2.4 + seed) * ry * 0.08 : 0);
  const bodyC: P = [cx - rx * 0.05, y0 + ry * 0.08];
  const headR = Math.min(rx * 0.16, ry * 0.22);
  const head: P = [cx + rx * 0.5, y0 - ry * 0.38];
  if (parts.has('tail')) {
    let d = '';
    for (let k = 0; k < 3; k += 1)
      d += ` ${poly([
        [cx - rx * 0.45, y0 + ry * 0.15],
        [cx - rx * 0.95, y0 + ry * (0.05 + k * 0.16)],
      ])}`;
    ops.push({
      kind: 'path',
      d: d.trim(),
      stroke: 'edge',
      width: 2.2,
      alpha: 0.9,
    });
    anchors.tail = [cx - rx * 0.95, y0 + ry * 0.2];
  }
  if (parts.has('legs')) {
    let d = '';
    for (const side of [-1, 1]) {
      const stride = walking
        ? Math.sin(t * 5 + (side > 0 ? Math.PI : 0)) * rx * 0.1
        : 0;
      const hip: P = [bodyC[0] + side * rx * 0.06, y0 + ry * 0.3];
      const foot: P = flying
        ? [hip[0] - rx * 0.12, y0 + ry * 0.45]
        : [hip[0] + stride, y0 + ry * 0.9];
      d += ` ${poly([hip, foot])}`;
      if (!flying)
        d += ` ${poly([
          [foot[0] - rx * 0.05, foot[1]],
          [foot[0] + rx * 0.1, foot[1]],
        ])}`;
      if (side > 0) anchors.legs = foot;
    }
    ops.push({
      kind: 'path',
      d: d.trim(),
      stroke: 'edge',
      width: 1.8,
      alpha: 0.9,
    });
  }
  ops.push({
    kind: 'path',
    d: ellipse(bodyC[0], bodyC[1], rx * 0.5, ry * 0.3, -0.22),
    fill: 'body',
    fillAlpha: 0.92,
    stroke: 'edge',
    width: 1.6,
  });
  if (parts.has('spots'))
    spots(ops, bodyC[0], bodyC[1], rx * 0.4, ry * 0.25, seed, 5);
  if (parts.has('wings')) {
    const root: P = [cx, y0 - ry * 0.12];
    if (flying) {
      const angle = -Math.PI / 2 + Math.sin(t * 2.6) * 0.7;
      const length = Math.min(rx * 0.75, ry * 0.9);
      const wing = (a: number, alpha: number) => {
        const tip = polar(root, a, length);
        ops.push({
          kind: 'path',
          d: `M ${pt(root)} Q ${pt(polar(root, a - 0.35, length * 0.6))} ${pt(tip)} Q ${pt(polar(root, a + 0.4, length * 0.65))} ${pt([root[0] - rx * 0.28, root[1] + ry * 0.12])} Z`,
          fill: 'body',
          fillAlpha: 0.75 * alpha,
          stroke: 'edge',
          width: 1.4,
          alpha,
        });
        return tip;
      };
      wing(angle + 0.5, 0.45);
      anchors.wings = wing(angle, 1);
    } else {
      ops.push({
        kind: 'path',
        d: ellipse(
          bodyC[0] - rx * 0.05,
          bodyC[1] - ry * 0.05,
          rx * 0.36,
          ry * 0.16,
          -0.3,
        ),
        fill: 'edge',
        fillAlpha: 0.35,
        stroke: 'edge',
        width: 1,
        alpha: 0.8,
      });
      anchors.wings = [bodyC[0] - rx * 0.3, bodyC[1] - ry * 0.1];
    }
  }
  // Neck and head.
  ops.push({
    kind: 'path',
    d: poly([[cx + rx * 0.3, y0 - ry * 0.12], head]),
    stroke: 'body',
    width: headR * 1.1,
  });
  ops.push({
    kind: 'path',
    d: ellipse(head[0], head[1], headR, headR),
    fill: 'body',
    fillAlpha: 1,
    stroke: 'edge',
    width: 1.6,
  });
  if (parts.has('beak')) {
    const tip: P = [head[0] + headR * 2.1, head[1] + headR * 0.15];
    ops.push({
      kind: 'path',
      d: `${poly([[head[0] + headR * 0.75, head[1] - headR * 0.2], tip, [head[0] + headR * 0.75, head[1] + headR * 0.4]])} Z`,
      fill: 'accent',
      fillAlpha: 0.95,
    });
    anchors.beak = tip;
  }
  const eye: P = [head[0] + headR * 0.35, head[1] - headR * 0.25];
  dot(ops, eye, headR * 0.28, 'ink', 0.95);
  anchors.head = head;
  anchors.body = bodyC;
  anchors.eye = eye;
  anchors.edge = [bodyC[0], bodyC[1] - ry * 0.3];
}

/* ── quadruped: a body on four legs with a head and a tail ────────── */

export function quadrupedFigure(
  f: Frame,
  ops: FigureOp[],
  anchors: Anchors,
): void {
  const { cx, cy, rx, ry, t, seed, parts, manner } = f;
  const walking = manner === 'walk' || manner === 'crawl';
  const bob = walking ? Math.sin(t * 5) * ry * 0.02 : 0;
  const bodyC: P = [cx - rx * 0.05, cy - ry * 0.05 + bob];
  const ground = cy + ry * 0.92;
  if (parts.has('legs')) {
    let d = '';
    const xs = [-0.42, -0.24, 0.16, 0.34];
    xs.forEach((k, i) => {
      const x = bodyC[0] + k * rx;
      const phase = i === 0 || i === 3 ? 0 : Math.PI;
      const swing = walking ? Math.sin(t * 5 + phase) * 0.4 : 0;
      const hip: P = [x, bodyC[1] + ry * 0.12];
      const knee: P = [x + Math.sin(swing) * ry * 0.3, hip[1] + ry * 0.36];
      const lift = walking
        ? Math.max(0, Math.cos(t * 5 + phase)) * ry * 0.06
        : 0;
      const foot: P = [x + Math.sin(swing) * ry * 0.62, ground - lift];
      d += ` ${poly([hip, knee, foot])}`;
      if (i === 3) anchors.legs = foot;
    });
    ops.push({
      kind: 'path',
      d: d.trim(),
      stroke: 'edge',
      width: Math.max(2, ry * 0.11),
      alpha: 0.95,
    });
  }
  if (parts.has('tail')) {
    const swish = Math.sin(t * 2.2 + seed) * ry * 0.12;
    const tip: P = [cx - rx * 0.92, cy + ry * 0.25 + swish];
    ops.push({
      kind: 'path',
      d: curve(
        [cx - rx * 0.58, bodyC[1] - ry * 0.15],
        [cx - rx * 0.9, bodyC[1] - ry * 0.45 + swish],
        tip,
      ),
      stroke: 'edge',
      width: 2.4,
      alpha: 0.95,
    });
    anchors.tail = tip;
  }
  ops.push({
    kind: 'path',
    d: ellipse(bodyC[0], bodyC[1], rx * 0.56, ry * 0.32),
    fill: 'body',
    fillAlpha: 0.92,
    stroke: 'edge',
    width: 1.8,
  });
  if (parts.has('stripes'))
    stripes(ops, bodyC[0], bodyC[1], rx * 0.56, ry * 0.32, 5, -0.7, 0.7);
  if (parts.has('spots'))
    spots(ops, bodyC[0], bodyC[1], rx * 0.5, ry * 0.28, seed, 7);
  // Neck and head.
  const head: P = [cx + rx * 0.66, cy - ry * 0.38 + bob];
  ops.push({
    kind: 'path',
    d: poly([
      [cx + rx * 0.4, bodyC[1] - ry * 0.12],
      [cx + rx * 0.58, head[1] + ry * 0.05],
    ]),
    stroke: 'body',
    width: ry * 0.3,
  });
  ops.push({
    kind: 'path',
    d: ellipse(head[0], head[1], rx * 0.2, ry * 0.15, 0.25),
    fill: 'body',
    fillAlpha: 1,
    stroke: 'edge',
    width: 1.6,
  });
  if (parts.has('ears')) {
    let d = '';
    for (const k of [-0.16, 0.0]) {
      const base: P = [head[0] + k * rx, head[1] - ry * 0.1];
      d += ` ${poly([
        [base[0] - rx * 0.04, base[1]],
        [base[0], base[1] - ry * 0.22],
        [base[0] + rx * 0.05, base[1] + ry * 0.02],
      ])} Z`;
    }
    ops.push({
      kind: 'path',
      d: d.trim(),
      fill: 'body',
      fillAlpha: 1,
      stroke: 'edge',
      width: 1.3,
    });
    anchors.ears = [head[0] - rx * 0.16, head[1] - ry * 0.32];
  }
  if (parts.has('horns')) {
    let d = '';
    for (const k of [-0.2, -0.02]) {
      const base: P = [head[0] + k * rx, head[1] - ry * 0.12];
      d += ` ${curve(base, [base[0] - rx * 0.1, base[1] - ry * 0.3], [base[0] + rx * 0.02, base[1] - ry * 0.42])}`;
    }
    ops.push({
      kind: 'path',
      d: d.trim(),
      stroke: 'ink',
      width: 2.2,
      alpha: 0.85,
    });
    anchors.horns = [head[0] - rx * 0.1, head[1] - ry * 0.45];
  }
  const eye: P = [head[0] + rx * 0.06, head[1] - ry * 0.04];
  dot(ops, eye, Math.max(1.5, ry * 0.045), 'ink', 0.95);
  anchors.head = head;
  anchors.body = bodyC;
  anchors.back = [bodyC[0], bodyC[1] - ry * 0.32];
  anchors.eye = eye;
  anchors.edge = [bodyC[0], bodyC[1] - ry * 0.32];
}

/* ── segmented: a chain that ripples along ────────────────────────── */

export function segmentedFigure(
  f: Frame,
  ops: FigureOp[],
  anchors: Anchors,
): void {
  const { cx, cy, rx, ry, t, seed, parts, manner } = f;
  const moving = manner !== 'still';
  const n = 12;
  const centres: P[] = [];
  const radii: number[] = [];
  for (let i = 0; i < n; i += 1) {
    const u = i / (n - 1);
    const x = cx - rx * 0.88 + u * rx * 1.76;
    const wave =
      Math.sin(u * Math.PI * 2.2 - (moving ? t * 2.8 : 0) + seed) * ry * 0.4;
    centres.push([x, cy + wave]);
    radii.push(Math.min(ry * 0.24, rx * 0.11) * (0.6 + 0.5 * u));
  }
  if (parts.has('legs')) {
    let d = '';
    centres.forEach((c, i) => {
      if (i % 2 || i === n - 1) return;
      const step = moving ? Math.sin(t * 6 + i) * radii[i] * 0.4 : 0;
      d += ` ${poly([
        [c[0] - radii[i] * 0.3 + step, c[1] + radii[i] * 0.6],
        [c[0] - radii[i] * 0.5 + step, c[1] + radii[i] * 1.5],
      ])}`;
      d += ` ${poly([
        [c[0] + radii[i] * 0.3 - step, c[1] + radii[i] * 0.6],
        [c[0] + radii[i] * 0.5 - step, c[1] + radii[i] * 1.5],
      ])}`;
    });
    ops.push({
      kind: 'path',
      d: d.trim(),
      stroke: 'edge',
      width: 1.2,
      alpha: 0.85,
    });
  }
  centres.forEach((c, i) => {
    ops.push({
      kind: 'path',
      d: ellipse(c[0], c[1], radii[i], radii[i]),
      fill: 'body',
      fillAlpha: parts.has('stripes') && i % 2 ? 0.55 : 0.95,
      stroke: 'edge',
      width: 1.4,
    });
  });
  if (parts.has('spots')) {
    const points: P[] = centres
      .filter((_, i) => i % 3 === 1)
      .map((c, i) => [c[0], c[1] - radii[i * 3 + 1] * 0.3]);
    ops.push({
      kind: 'dots',
      points,
      r: Math.max(1.2, radii[6] * 0.3),
      fill: 'ink',
      alpha: 0.5,
    });
  }
  const head = centres[n - 1];
  const eye: P = [head[0] + radii[n - 1] * 0.3, head[1] - radii[n - 1] * 0.35];
  dot(ops, eye, Math.max(1.3, radii[n - 1] * 0.22), 'ink', 0.95);
  anchors.head = head;
  anchors.body = centres[Math.floor(n / 2)];
  anchors.eye = eye;
  anchors.edge = [centres[0][0], centres[0][1]];
}

/* ── person: a head, a body, and limbs that walk ──────────────────── */

export function personFigure(
  f: Frame,
  ops: FigureOp[],
  anchors: Anchors,
): void {
  const { cx, cy, rx, ry, t, seed, manner } = f;
  const walking = manner === 'walk';
  const headR = Math.min(rx * 0.32, ry * 0.12);
  const bob = walking ? Math.abs(Math.sin(t * 5 + seed)) * ry * 0.015 : 0;
  const head: P = [cx, cy - ry + headR + bob];
  const shoulderY = head[1] + headR * 1.45;
  const hipY = cy + ry * 0.1 + bob;
  const shoulders = Math.min(rx * 0.34, ry * 0.2);
  const hips = shoulders * 0.72;
  // Legs, then the body over them, then the arms.
  let legs = '';
  for (const side of [-1, 1]) {
    const stride = walking
      ? Math.sin(t * 5 + seed + (side > 0 ? Math.PI : 0)) * 0.42
      : side * 0.06;
    const hip: P = [cx + side * hips * 0.5, hipY];
    const knee = polar(hip, Math.PI / 2 + stride, ry * 0.42);
    const foot = polar(knee, Math.PI / 2 + stride * 0.55, ry * 0.42);
    legs += ` ${poly([hip, knee, foot])}`;
    if (side > 0) anchors.legs = foot;
  }
  ops.push({
    kind: 'path',
    d: legs.trim(),
    stroke: 'edge',
    width: Math.max(2.5, headR * 0.5),
    alpha: 0.95,
  });
  ops.push({
    kind: 'path',
    d: `${poly([
      [cx - shoulders, shoulderY],
      [cx + shoulders, shoulderY],
      [cx + hips, hipY + headR * 0.4],
      [cx - hips, hipY + headR * 0.4],
    ])} Z`,
    fill: 'body',
    fillAlpha: 0.92,
    stroke: 'edge',
    width: 1.6,
  });
  let arms = '';
  for (const side of [-1, 1]) {
    const swing = walking
      ? Math.sin(t * 5 + seed + (side > 0 ? 0 : Math.PI)) * 0.5
      : 0;
    const shoulder: P = [cx + side * shoulders * 0.9, shoulderY + headR * 0.2];
    const elbow = polar(shoulder, Math.PI / 2 + side * 0.18 + swing, ry * 0.3);
    const hand = polar(
      elbow,
      Math.PI / 2 + side * 0.1 + swing * 1.3,
      ry * 0.28,
    );
    arms += ` ${poly([shoulder, elbow, hand])}`;
    if (side > 0) anchors.arms = hand;
  }
  ops.push({
    kind: 'path',
    d: arms.trim(),
    stroke: 'edge',
    width: Math.max(2.2, headR * 0.42),
    alpha: 0.95,
  });
  ops.push({
    kind: 'path',
    d: ellipse(head[0], head[1], headR, headR * 1.06),
    fill: 'body',
    fillAlpha: 1,
    stroke: 'edge',
    width: 1.6,
  });
  dot(
    ops,
    [head[0] - headR * 0.32, head[1] - headR * 0.1],
    headR * 0.12,
    'ink',
    0.9,
  );
  dot(
    ops,
    [head[0] + headR * 0.32, head[1] - headR * 0.1],
    headR * 0.12,
    'ink',
    0.9,
  );
  anchors.head = head;
  anchors.body = [cx, (shoulderY + hipY) / 2];
  anchors.edge = [cx - shoulders, shoulderY];
}
