// Generated by easyread/scripts/visual-living.mjs. Do not edit; edit the client's copy.
/**
 * The organic outlines: a cell, a swimmer, a river system, rock strata,
 * a crystal, a tank, a coastline, a field of flow. Each is a recipe with
 * a few numbers, never a wrong picture.
 */
import {
  closed,
  line,
  rnd,
  through,
  type FigureOp,
  type Frame,
} from './figures-ops';

/* ── blob: a soft closed shape that breathes ──────────────────────── */

function blobRadius(f: Frame, th: number): number {
  const s = f.seed;
  let r =
    1 +
    0.09 * Math.sin(3 * th + f.t * 0.9 + s) +
    0.06 * Math.sin(5 * th - f.t * 1.3 + s * 2);
  if (f.parts.has('bulge')) {
    // An arm that pushes out and draws back, twice a cycle.
    const reach = 0.5 + 0.5 * Math.sin(f.t * 0.55 + s);
    for (const dir of [0.55, -0.75]) {
      let d = th - dir;
      while (d > Math.PI) d -= Math.PI * 2;
      while (d < -Math.PI) d += Math.PI * 2;
      r += 0.45 * reach * Math.exp(-(d * d) / 0.08);
    }
  }
  return r;
}

export function blobOutline(f: Frame, scale = 1): [number, number][] {
  const points: [number, number][] = [];
  for (let i = 0; i < 64; i += 1) {
    const th = (i / 64) * Math.PI * 2;
    const r = blobRadius(f, th) * scale;
    points.push([
      f.cx + Math.cos(th) * f.rx * r,
      f.cy + Math.sin(th) * f.ry * r,
    ]);
  }
  return points;
}

export function bodyOutline(f: Frame, scale = 1): [number, number][] {
  const bend = f.manner === 'swim' ? Math.sin(f.t * 2.2) * 0.1 : 0;
  const points: [number, number][] = [];
  for (let i = 0; i < 56; i += 1) {
    const th = (i / 56) * Math.PI * 2;
    // A spindle: fuller at the front, drawn out behind.
    const taper = 1 - 0.24 * Math.cos(th);
    points.push([
      f.cx + Math.cos(th) * f.rx * scale,
      f.cy +
        Math.sin(th) * f.ry * taper * scale +
        bend * f.ry * Math.cos(th) * 1.4,
    ]);
  }
  return points;
}

/** The parts that sit on a closed outline: both the blob and the body wear them. */
export function skin(
  f: Frame,
  outline: (scale: number) => [number, number][],
  ops: FigureOp[],
  anchors: Record<string, [number, number]>,
): void {
  const { cx, cy, rx, ry, t, seed, parts } = f;
  if (parts.has('hairs')) {
    // A wave of short strokes travels round the edge, as cilia beat.
    const n = 60;
    const length = Math.min(rx, ry) * 0.17;
    const edge = outline(1);
    let d = '';
    for (let i = 0; i < n; i += 1) {
      const p = edge[Math.floor((i / n) * edge.length)];
      const th = Math.atan2(p[1] - cy, p[0] - cx);
      const beat = Math.sin(t * 7 - i * 0.42) * 0.7;
      const a = th + beat;
      d += ` ${line(p, [p[0] + Math.cos(a) * length, p[1] + Math.sin(a) * length])}`;
    }
    ops.push({
      kind: 'path',
      d: d.trim(),
      stroke: 'edge',
      width: 1.1,
      alpha: 0.85,
    });
  }
  const shape = outline(1);
  ops.push({
    kind: 'path',
    d: closed(shape),
    fill: 'body',
    fillAlpha: 0.55,
    stroke: 'edge',
    width: 2.2,
  });
  anchors.edge = shape[Math.floor(shape.length * 0.75)];
  if (parts.has('membrane'))
    ops.push({
      kind: 'path',
      d: closed(outline(0.88)),
      stroke: 'edge',
      width: 1.1,
      alpha: 0.5,
    });
  if (parts.has('whip')) {
    // One long tail, whipping from the back.
    const from: [number, number] = [cx - rx * 0.95, cy];
    const points: [number, number][] = [];
    for (let i = 0; i <= 14; i += 1) {
      const u = i / 14;
      points.push([
        from[0] - u * rx * 1.1,
        from[1] + Math.sin(u * 7 - t * 6) * ry * 0.22 * u,
      ]);
    }
    ops.push({
      kind: 'path',
      d: through(points),
      stroke: 'edge',
      width: 1.6,
      alpha: 0.9,
    });
    anchors.whip = points[points.length - 1];
  }
  if (parts.has('grains')) {
    const points: [number, number][] = [];
    for (let i = 0; i < 13; i += 1) {
      if (f.manner === 'stream') {
        // The inside streams round, the way a cell's contents circulate.
        const u = (t * 0.06 + i / 13) % 1;
        const th = u * Math.PI * 2;
        const k = 0.4 + 0.34 * rnd(seed, i);
        points.push([cx + Math.cos(th) * rx * k, cy + Math.sin(th) * ry * k]);
      } else {
        const th = rnd(seed, i) * Math.PI * 2;
        const k = 0.2 + 0.55 * rnd(seed, i + 40);
        points.push([
          cx + Math.cos(th) * rx * k,
          cy + Math.sin(th) * ry * k + Math.sin(t + i) * 0.6,
        ]);
      }
    }
    ops.push({
      kind: 'dots',
      points,
      r: Math.max(1.4, rx * 0.035),
      fill: 'accent',
      alpha: 0.75,
    });
  }
  if (parts.has('core')) {
    const kx = cx - rx * 0.2;
    const ky = cy + ry * 0.12;
    const wobble = 1 + Math.sin(t * 0.7 + seed) * 0.04;
    const points: [number, number][] = [];
    for (let i = 0; i < 24; i += 1) {
      const th = (i / 24) * Math.PI * 2;
      points.push([
        kx + Math.cos(th) * rx * 0.3 * wobble,
        ky + Math.sin(th) * ry * 0.22 * wobble,
      ]);
    }
    ops.push({
      kind: 'path',
      d: closed(points),
      fill: 'core',
      fillAlpha: 0.6,
      stroke: 'core',
      width: 1.5,
    });
    anchors.core = [kx, ky];
  }
  if (parts.has('pockets')) {
    // Rings that swell and empty, as a cell's vacuoles do.
    [0.55, -0.5].forEach((side, i) => {
      const px = cx + rx * side;
      const py = cy - ry * (0.3 + i * 0.12);
      const swell = (Math.sin(t * 1.9 + i * 2.2) + 1) / 2;
      const r = Math.max(2.5, rx * (0.07 + 0.05 * swell));
      const points: [number, number][] = [];
      for (let k = 0; k < 18; k += 1) {
        const th = (k / 18) * Math.PI * 2;
        points.push([px + Math.cos(th) * r, py + Math.sin(th) * r]);
      }
      ops.push({
        kind: 'path',
        d: closed(points),
        stroke: 'accent',
        width: 1.4,
        alpha: 0.85,
      });
      if (i === 0) anchors.pockets = [px, py];
    });
  }
  if (parts.has('mouth')) {
    const a: [number, number] = [cx - rx * 0.5, cy + ry * 0.5];
    const b: [number, number] = [cx + rx * 0.12, cy + ry * 0.2];
    ops.push({
      kind: 'path',
      d: `M ${a[0].toFixed(2)} ${a[1].toFixed(2)} Q ${cx.toFixed(2)} ${(cy + ry * 0.62).toFixed(2)} ${b[0].toFixed(2)} ${b[1].toFixed(2)}`,
      stroke: 'edge',
      width: 2,
      alpha: 0.9,
    });
    anchors.mouth = [cx - rx * 0.2, cy + ry * 0.5];
  }
}

/* ── branch: a trunk dividing again and again ─────────────────────── */

export function branchFigure(
  f: Frame,
  ops: FigureOp[],
  anchors: Record<string, [number, number]>,
): void {
  const { cx, cy, rx, ry, t, seed, parts } = f;
  const base: [number, number] = [cx, cy + ry * 0.92];
  const tips: [number, number][] = [];
  const forks: [number, number][] = [];
  const grown = f.manner === 'grow' ? Math.min(1, 0.25 + t * 0.22) : 1;
  const limb = (
    from: [number, number],
    angle: number,
    length: number,
    width: number,
    depth: number,
    key: number,
  ) => {
    const shown = Math.max(0, Math.min(1, grown * 4 - depth));
    if (shown <= 0) return;
    const sway = Math.sin(t * 0.8 + key) * 0.05 * (depth + 1);
    const a = angle + sway;
    const to: [number, number] = [
      from[0] + Math.cos(a) * length * shown,
      from[1] + Math.sin(a) * length * shown,
    ];
    const mid: [number, number] = [
      (from[0] + to[0]) / 2 + Math.cos(a + Math.PI / 2) * length * 0.08,
      (from[1] + to[1]) / 2 + Math.sin(a + Math.PI / 2) * length * 0.08,
    ];
    ops.push({
      kind: 'path',
      d: `M ${from[0].toFixed(2)} ${from[1].toFixed(2)} Q ${mid[0].toFixed(2)} ${mid[1].toFixed(2)} ${to[0].toFixed(2)} ${to[1].toFixed(2)}`,
      stroke: 'edge',
      width: Math.max(1, width),
    });
    if (depth >= 3 || shown < 1) {
      tips.push(to);
      return;
    }
    forks.push(to);
    const spread = 0.42 + rnd(seed, key) * 0.2;
    limb(to, a - spread, length * 0.74, width * 0.66, depth + 1, key * 2 + 1);
    limb(to, a + spread, length * 0.74, width * 0.66, depth + 1, key * 2 + 2);
  };
  limb(base, -Math.PI / 2, ry * 0.52, Math.max(3, rx * 0.06), 0, seed % 17);
  if (parts.has('roots')) {
    limb(base, Math.PI / 2 - 0.5, ry * 0.2, 2.4, 2, 91);
    limb(base, Math.PI / 2 + 0.5, ry * 0.2, 2.4, 2, 92);
  }
  if (parts.has('grains') && tips.length)
    ops.push({
      kind: 'dots',
      points: tips,
      r: Math.max(2, rx * 0.045),
      fill: 'accent',
      alpha: 0.85,
    });
  if (parts.has('joints') && forks.length)
    ops.push({ kind: 'dots', points: forks, r: 2.2, fill: 'core', alpha: 0.9 });
  if (parts.has('core') && forks.length) anchors.core = forks[0];
  anchors.edge = tips[0] ?? base;
  anchors.base = base;
}

/* ── layers: bands stacked one on another ─────────────────────────── */

export function layersFigure(
  f: Frame,
  ops: FigureOp[],
  anchors: Record<string, [number, number]>,
): void {
  const { cx, cy, rx, ry, t, seed, parts } = f;
  const bands = 4;
  const left = cx - rx;
  const right = cx + rx;
  const top = cy - ry;
  const height = (ry * 2) / bands;
  const edge = (i: number): [number, number][] => {
    const points: [number, number][] = [];
    for (let k = 0; k <= 10; k += 1) {
      const x = left + (k / 10) * rx * 2;
      points.push([
        x,
        top +
          i * height +
          Math.sin(k * 0.8 + i * 1.7 + seed) * height * 0.13 +
          Math.sin(t * 0.3 + i) * 0.4,
      ]);
    }
    return points;
  };
  for (let i = 0; i < bands; i += 1) {
    const upper = edge(i);
    const lower = i === bands - 1 ? null : edge(i + 1);
    const bottom = lower
      ? [...lower].reverse()
      : ([
          [right, top + ry * 2],
          [left, top + ry * 2],
        ] as [number, number][]);
    const d = `${through(upper)} L ${bottom[0][0].toFixed(2)} ${bottom[0][1].toFixed(2)} ${through(bottom).slice(1)} Z`;
    ops.push({
      kind: 'path',
      d,
      fill: i % 2 === 0 ? 'body' : 'core',
      fillAlpha: 0.3 + 0.12 * (i % 2),
      stroke: 'edge',
      width: 1.4,
      alpha: 0.95,
    });
    if (i === 1) anchors.core = [cx, top + i * height + height / 2];
  }
  if (parts.has('cracks')) {
    let d = '';
    for (let i = 0; i < 3; i += 1) {
      const x = left + rx * (0.4 + 1.2 * rnd(seed, i));
      const y = top + height * (0.6 + i * 0.9);
      d += ` ${line([x, y], [x + 6 - 12 * rnd(seed, i + 9), y + height * 0.9])}`;
    }
    ops.push({
      kind: 'path',
      d: d.trim(),
      stroke: 'edge',
      width: 1.2,
      alpha: 0.6,
    });
  }
  if (parts.has('grains')) {
    const points: [number, number][] = [];
    for (let i = 0; i < 16; i += 1)
      points.push([
        left + rnd(seed, i) * rx * 2,
        top + height * (1 + rnd(seed, i + 30) * (bands - 1)),
      ]);
    ops.push({ kind: 'dots', points, r: 1.5, fill: 'accent', alpha: 0.6 });
  }
  anchors.edge = [cx, top];
}

/* ── lattice: nodes joined in a mesh ──────────────────────────────── */

export function latticeFigure(
  f: Frame,
  ops: FigureOp[],
  anchors: Record<string, [number, number]>,
): void {
  const { cx, cy, rx, ry, t, parts, manner } = f;
  const cols = 4;
  const rows = 3;
  const gx = (rx * 1.7) / (cols - 1);
  const gy = (ry * 1.6) / (rows - 1);
  const at = (c: number, r: number): [number, number] => [
    cx - (rx * 1.7) / 2 + c * gx + (r % 2 ? gx * 0.22 : 0),
    cy - (ry * 1.6) / 2 + r * gy,
  ];
  let d = '';
  for (let r = 0; r < rows; r += 1)
    for (let c = 0; c < cols; c += 1) {
      if (c + 1 < cols) d += ` ${line(at(c, r), at(c + 1, r))}`;
      if (r + 1 < rows) d += ` ${line(at(c, r), at(c, r + 1))}`;
    }
  ops.push({
    kind: 'path',
    d: d.trim(),
    stroke: 'edge',
    width: 1.4,
    alpha: 0.7,
  });
  const points: [number, number][] = [];
  for (let r = 0; r < rows; r += 1)
    for (let c = 0; c < cols; c += 1) points.push(at(c, r));
  const breathe = manner === 'pulse' ? 1 + Math.sin(t * 2) * 0.12 : 1;
  ops.push({
    kind: 'dots',
    points,
    r: Math.max(2.5, rx * 0.055) * breathe,
    fill: 'body',
    alpha: 0.95,
  });
  if (parts.has('joints'))
    ops.push({
      kind: 'dots',
      points,
      r: Math.max(1.2, rx * 0.022),
      fill: 'core',
      alpha: 0.9,
    });
  if (parts.has('core')) {
    const middle = at(1, 1);
    ops.push({
      kind: 'dots',
      points: [middle],
      r: Math.max(4, rx * 0.085),
      fill: 'core',
      alpha: 0.95,
    });
    anchors.core = middle;
  }
  if (manner === 'stream') {
    // A pulse runs along the mesh, one link at a time.
    const lit = Math.floor(t * 2) % points.length;
    ops.push({
      kind: 'dots',
      points: [points[lit]],
      r: Math.max(4, rx * 0.08),
      fill: 'accent',
      alpha: 0.9,
    });
  }
  anchors.edge = at(0, 0);
}

/* ── vessel: a container filled to a level ────────────────────────── */

export function vesselFigure(
  f: Frame,
  ops: FigureOp[],
  anchors: Record<string, [number, number]>,
): void {
  const { cx, cy, rx, ry, t, seed, parts } = f;
  const top = cy - ry * 0.86;
  const bottom = cy + ry * 0.9;
  const halfTop = rx * 0.78;
  const halfBottom = rx * 0.64;
  const wall: [number, number][] = [
    [cx - halfTop, top],
    [cx - halfBottom, bottom],
    [cx + halfBottom, bottom],
    [cx + halfTop, top],
  ];
  const levelY = parts.has('level') ? top + (bottom - top) * 0.42 : bottom;
  if (parts.has('level')) {
    const surface: [number, number][] = [];
    const halfAt = (y: number) =>
      halfTop + ((halfBottom - halfTop) * (y - top)) / (bottom - top);
    const half = halfAt(levelY);
    for (let i = 0; i <= 10; i += 1) {
      const x = cx - half + (i / 10) * half * 2;
      surface.push([x, levelY + Math.sin(i * 0.9 + t * 1.6) * 1.8]);
    }
    const d = `${through(surface)} L ${(cx + halfBottom).toFixed(2)} ${bottom.toFixed(2)} L ${(cx - halfBottom).toFixed(2)} ${bottom.toFixed(2)} Z`;
    ops.push({
      kind: 'path',
      d,
      fill: 'body',
      fillAlpha: 0.6,
      stroke: 'accent',
      width: 1.6,
    });
    anchors.level = [cx, levelY];
  }
  ops.push({
    kind: 'path',
    d: `M ${wall[0][0].toFixed(2)} ${wall[0][1].toFixed(2)} L ${wall[1][0].toFixed(2)} ${wall[1][1].toFixed(2)} Q ${cx.toFixed(2)} ${(bottom + ry * 0.1).toFixed(2)} ${wall[2][0].toFixed(2)} ${wall[2][1].toFixed(2)} L ${wall[3][0].toFixed(2)} ${wall[3][1].toFixed(2)}`,
    stroke: 'edge',
    width: 2.4,
  });
  if (parts.has('mouth'))
    ops.push({
      kind: 'path',
      d: `M ${(cx - halfTop - 3).toFixed(2)} ${top.toFixed(2)} L ${(cx + halfTop + 3).toFixed(2)} ${top.toFixed(2)}`,
      stroke: 'edge',
      width: 2.4,
    });
  if (parts.has('grains')) {
    // Bubbles rise and start again, so the picture never runs out.
    const points: [number, number][] = [];
    for (let i = 0; i < 7; i += 1) {
      const u = (t * 0.22 + rnd(seed, i)) % 1;
      points.push([
        cx + (rnd(seed, i + 12) - 0.5) * halfBottom * 1.4,
        bottom - u * (bottom - levelY),
      ]);
    }
    ops.push({ kind: 'dots', points, r: 2, fill: 'accent', alpha: 0.7 });
  }
  if (parts.has('core')) anchors.core = [cx, (levelY + bottom) / 2];
  anchors.edge = [cx, top];
}

/* ── terrain: ground seen from the side ───────────────────────────── */

export function terrainFigure(
  f: Frame,
  ops: FigureOp[],
  anchors: Record<string, [number, number]>,
): void {
  const { cx, cy, rx, ry, t, seed, parts } = f;
  const left = cx - rx;
  const bottom = cy + ry;
  const profile = (drop: number): [number, number][] => {
    const points: [number, number][] = [];
    for (let i = 0; i <= 16; i += 1) {
      const u = i / 16;
      const x = left + u * rx * 2;
      const y =
        cy -
        ry * 0.35 * Math.sin(u * 3.1 + seed) -
        ry * 0.2 * Math.sin(u * 6.3 + seed * 2) +
        drop +
        Math.sin(t * 0.25 + u * 4) * 0.5;
      points.push([x, y]);
    }
    return points;
  };
  const layers = parts.has('level') ? 3 : 2;
  for (let i = layers - 1; i >= 0; i -= 1) {
    const line0 = profile(i * ry * 0.3);
    const d = `${through(line0)} L ${(cx + rx).toFixed(2)} ${bottom.toFixed(2)} L ${left.toFixed(2)} ${bottom.toFixed(2)} Z`;
    ops.push({
      kind: 'path',
      d,
      fill: i === 0 ? 'body' : 'core',
      fillAlpha: i === 0 ? 0.6 : 0.3 + i * 0.08,
      stroke: i === 0 ? 'edge' : undefined,
      width: 2,
    });
  }
  if (parts.has('cracks')) {
    let d = '';
    for (let i = 0; i < 3; i += 1) {
      const x = left + rx * (0.5 + 1.1 * rnd(seed, i));
      const y = cy + ry * 0.35;
      d += ` ${line([x, y], [x + 5 - 10 * rnd(seed, i + 5), bottom - 2])}`;
    }
    ops.push({
      kind: 'path',
      d: d.trim(),
      stroke: 'edge',
      width: 1.1,
      alpha: 0.5,
    });
  }
  if (parts.has('grains')) {
    const points: [number, number][] = [];
    for (let i = 0; i < 14; i += 1)
      points.push([
        left + rnd(seed, i) * rx * 2,
        cy + ry * (0.1 + 0.8 * rnd(seed, i + 20)),
      ]);
    ops.push({ kind: 'dots', points, r: 1.5, fill: 'accent', alpha: 0.6 });
  }
  const crest = profile(0)[8];
  anchors.edge = crest;
  anchors.core = [cx, cy + ry * 0.5];
}

/* ── field: lines of flow across a space ──────────────────────────── */

export function fieldFigure(
  f: Frame,
  ops: FigureOp[],
  anchors: Record<string, [number, number]>,
): void {
  const { cx, cy, rx, ry, t, parts } = f;
  const lines = 5;
  for (let i = 0; i < lines; i += 1) {
    const offset = (i - (lines - 1) / 2) * ((ry * 1.7) / lines);
    const points: [number, number][] = [];
    for (let k = 0; k <= 14; k += 1) {
      const u = k / 14;
      const x = cx - rx + u * rx * 2;
      points.push([
        x,
        cy + offset + Math.sin(u * 4 + t * 0.7 + i * 0.6) * ry * 0.13,
      ]);
    }
    ops.push({
      kind: 'path',
      d: through(points),
      stroke: 'edge',
      width: 1.6,
      alpha: 0.55,
    });
    if (parts.has('grains')) {
      const dots: [number, number][] = [];
      for (let j = 0; j < 3; j += 1) {
        const u = (t * 0.16 + i * 0.13 + j * 0.34) % 1;
        const x = cx - rx + u * rx * 2;
        dots.push([
          x,
          cy + offset + Math.sin(u * 4 + t * 0.7 + i * 0.6) * ry * 0.13,
        ]);
      }
      ops.push({
        kind: 'dots',
        points: dots,
        r: 2.4,
        fill: 'accent',
        alpha: 0.9,
      });
    }
  }
  if (parts.has('core')) {
    ops.push({
      kind: 'dots',
      points: [[cx - rx * 0.86, cy]],
      r: Math.max(4, rx * 0.08),
      fill: 'core',
      alpha: 0.95,
    });
    anchors.core = [cx - rx * 0.86, cy];
  }
  anchors.edge = [cx, cy - ry * 0.8];
}
