// Generated by easyread/scripts/visual-living.mjs. Do not edit; edit the client's copy.
/**
 * What every built figure and mechanism is made of: draw operations a
 * canvas paints while it moves and an SVG writes while it sits still,
 * and the small helpers every recipe draws with.
 *
 * Every shape is a pure function of the clock. Nothing accumulates, so
 * seeking to a moment draws exactly what that moment looked like.
 */
/** What a figure is drawn from: the element's box and recipe, nothing more. */
export interface FigureSpec {
  x: number;
  y: number;
  w: number;
  h: number;
  outline: string;
  parts: string[];
  manner: string;
  seed: number;
}

/**
 * The colours a drawing names: the thing's own body and edge, a second
 * colour for a core, a bright mark, the stage's dark for eyes and
 * marks on a body, and a warm colour for what is wrong or hot.
 */
export type FigureRole = 'body' | 'edge' | 'core' | 'accent' | 'ink' | 'warm';

export type FigureOp =
  | {
      kind: 'path';
      d: string;
      fill?: FigureRole;
      fillAlpha?: number;
      stroke?: FigureRole;
      width?: number;
      alpha?: number;
    }
  | {
      kind: 'dots';
      points: [number, number][];
      r: number;
      fill: FigureRole;
      alpha?: number;
    };

export interface FigureDrawing {
  ops: FigureOp[];
  /** Where each named part sits, for a label that follows it. */
  anchors: Record<string, [number, number]>;
}

/** One number from a seed and a place, so a figure is the same every time it is drawn. */
export function rnd(seed: number, i: number): number {
  const x = Math.sin(seed * 127.1 + i * 311.7) * 43758.5453;
  return x - Math.floor(x);
}

/** A smooth closed path through the points, each corner rounded into the next. */
export function closed(points: [number, number][]): string {
  const n = points.length;
  if (n < 3) return '';
  const mid = (a: [number, number], b: [number, number]) =>
    `${((a[0] + b[0]) / 2).toFixed(2)} ${((a[1] + b[1]) / 2).toFixed(2)}`;
  let d = `M ${mid(points[n - 1], points[0])}`;
  for (let i = 0; i < n; i += 1) {
    const p = points[i];
    const q = points[(i + 1) % n];
    d += ` Q ${p[0].toFixed(2)} ${p[1].toFixed(2)} ${mid(p, q)}`;
  }
  return `${d} Z`;
}

/** A smooth open path through the points. */
export function through(points: [number, number][]): string {
  if (points.length < 2) return '';
  let d = `M ${points[0][0].toFixed(2)} ${points[0][1].toFixed(2)}`;
  for (let i = 1; i < points.length - 1; i += 1) {
    const p = points[i];
    const q = points[i + 1];
    d += ` Q ${p[0].toFixed(2)} ${p[1].toFixed(2)} ${((p[0] + q[0]) / 2).toFixed(2)} ${((p[1] + q[1]) / 2).toFixed(2)}`;
  }
  const last = points[points.length - 1];
  return `${d} L ${last[0].toFixed(2)} ${last[1].toFixed(2)}`;
}

export const line = (a: [number, number], b: [number, number]) =>
  `M ${a[0].toFixed(2)} ${a[1].toFixed(2)} L ${b[0].toFixed(2)} ${b[1].toFixed(2)}`;

/** How fast a manner moves, and whether it moves at all. */
export function pace(manner: string): number {
  switch (manner) {
    case 'still':
      return 0;
    case 'drift':
      return 0.5;
    case 'swim':
      return 1.1;
    case 'beat':
      return 1.4;
    case 'stream':
      return 1;
    case 'grow':
      return 0.45;
    case 'pulse':
      return 0.8;
    case 'flutter':
    case 'walk':
    case 'fly':
    case 'crawl':
    case 'sway':
    case 'hover':
      return 1;
    default:
      return 0.6;
  }
}

export interface Frame {
  cx: number;
  cy: number;
  rx: number;
  ry: number;
  t: number;
  seed: number;
  parts: Set<string>;
  manner: string;
}

/** An ellipse as a closed path. */
export function ellipse(
  cx: number,
  cy: number,
  rx: number,
  ry: number,
  rotate = 0,
): string {
  const points: [number, number][] = [];
  const cos = Math.cos(rotate);
  const sin = Math.sin(rotate);
  for (let i = 0; i < 24; i += 1) {
    const th = (i / 24) * Math.PI * 2;
    const x = Math.cos(th) * rx;
    const y = Math.sin(th) * ry;
    points.push([cx + x * cos - y * sin, cy + x * sin + y * cos]);
  }
  return closed(points);
}

/** A point written for a path. */
export const pt = (p: [number, number]) =>
  `${p[0].toFixed(2)} ${p[1].toFixed(2)}`;
