// Generated by easyread/scripts/visual-living.mjs. Do not edit; edit the client's copy.
/**
 * Things that grow: a plant with leaves, flowers and fruit on a stem,
 * and a tree with a trunk and a crown. Both sway.
 */
import { closed, pt, rnd, type FigureOp, type Frame } from './figures-ops';

type P = [number, number];
type Anchors = Record<string, P>;

/** A leaf: two curves from its base to its tip, and a vein down the middle. */
function leaf(ops: FigureOp[], base: P, tip: P, width: number): void {
  const dx = tip[0] - base[0];
  const dy = tip[1] - base[1];
  const len = Math.hypot(dx, dy) || 1;
  const nx = (-dy / len) * width;
  const ny = (dx / len) * width;
  const mid: P = [(base[0] + tip[0]) / 2, (base[1] + tip[1]) / 2];
  ops.push({
    kind: 'path',
    d: `M ${pt(base)} Q ${pt([mid[0] + nx, mid[1] + ny])} ${pt(tip)} Q ${pt([mid[0] - nx, mid[1] - ny])} ${pt(base)} Z`,
    fill: 'body',
    fillAlpha: 0.88,
    stroke: 'edge',
    width: 1.2,
  });
  ops.push({
    kind: 'path',
    d: `M ${pt(base)} L ${pt(tip)}`,
    stroke: 'edge',
    width: 0.9,
    alpha: 0.6,
  });
}

export function plantFigure(f: Frame, ops: FigureOp[], anchors: Anchors): void {
  const { cx, cy, rx, ry, t, seed, parts, manner } = f;
  const sway = manner === 'still' ? 0 : Math.sin(t * 1.3 + seed) * 0.12;
  const groundY = parts.has('roots') ? cy + ry * 0.6 : cy + ry * 0.95;
  const top: P = [cx + sway * rx * 0.9, cy - ry * 0.85];
  const control: P = [cx + sway * rx * 0.3, (groundY + top[1]) / 2];
  const base: P = [cx, groundY];
  const on = (u: number): P => [
    (1 - u) * (1 - u) * base[0] + 2 * (1 - u) * u * control[0] + u * u * top[0],
    (1 - u) * (1 - u) * base[1] + 2 * (1 - u) * u * control[1] + u * u * top[1],
  ];
  if (parts.has('roots')) {
    let d = '';
    for (let i = 0; i < 4; i += 1) {
      const side = i % 2 ? 1 : -1;
      const tip: P = [
        cx + side * rx * (0.15 + 0.35 * rnd(seed, i)),
        groundY + ry * (0.2 + 0.3 * rnd(seed, i + 8)),
      ];
      d += ` M ${pt(base)} Q ${pt([cx + side * rx * 0.1, groundY + ry * 0.12])} ${pt(tip)}`;
      if (i === 0) anchors.roots = tip;
    }
    ops.push({
      kind: 'path',
      d: d.trim(),
      stroke: 'edge',
      width: 1.4,
      alpha: 0.7,
    });
    ops.push({
      kind: 'path',
      d: `M ${(cx - rx * 0.7).toFixed(2)} ${groundY.toFixed(2)} L ${(cx + rx * 0.7).toFixed(2)} ${groundY.toFixed(2)}`,
      stroke: 'edge',
      width: 1,
      alpha: 0.35,
    });
  }
  ops.push({
    kind: 'path',
    d: `M ${pt(base)} Q ${pt(control)} ${pt(top)}`,
    stroke: 'edge',
    width: Math.max(2, rx * 0.05),
  });
  if (parts.has('leaves')) {
    [0.3, 0.5, 0.68, 0.84].forEach((u, i) => {
      const side = i % 2 ? 1 : -1;
      const at = on(u);
      const tip: P = [
        at[0] + side * rx * (0.5 - u * 0.2),
        at[1] - ry * (0.1 + sway * side * 0.3),
      ];
      leaf(ops, at, tip, Math.min(rx * 0.16, ry * 0.08));
      if (i === 1) anchors.leaves = tip;
    });
  }
  if (parts.has('fruit')) {
    const points: P[] = [0.45, 0.72].map((u, i) => {
      const at = on(u);
      return [at[0] + (i % 2 ? -1 : 1) * rx * 0.16, at[1] + ry * 0.08];
    });
    ops.push({
      kind: 'dots',
      points,
      r: Math.max(2.5, Math.min(rx, ry) * 0.09),
      fill: 'warm',
      alpha: 0.95,
    });
    anchors.fruit = points[0];
  }
  if (parts.has('flowers')) {
    const r = Math.max(3, Math.min(rx, ry) * 0.1);
    const petals: P[] = [];
    for (let i = 0; i < 6; i += 1) {
      const a = (i / 6) * Math.PI * 2 + t * 0.2;
      petals.push([
        top[0] + Math.cos(a) * r * 1.5,
        top[1] + Math.sin(a) * r * 1.5,
      ]);
    }
    ops.push({ kind: 'dots', points: petals, r, fill: 'warm', alpha: 0.9 });
    ops.push({
      kind: 'dots',
      points: [top],
      r: r * 0.8,
      fill: 'accent',
      alpha: 1,
    });
    anchors.flowers = top;
  }
  anchors.stem = on(0.5);
  anchors.top = top;
  anchors.edge = top;
}

export function treeFigure(f: Frame, ops: FigureOp[], anchors: Anchors): void {
  const { cx, cy, rx, ry, t, seed, parts } = f;
  const sway = f.manner === 'still' ? 0 : Math.sin(t * 0.9 + seed) * rx * 0.04;
  const groundY = parts.has('roots') ? cy + ry * 0.7 : cy + ry * 0.95;
  const trunkTop = cy - ry * 0.05;
  if (parts.has('roots')) {
    let d = '';
    for (let i = 0; i < 4; i += 1) {
      const side = i % 2 ? 1 : -1;
      const tip: P = [
        cx + side * rx * (0.2 + 0.4 * rnd(seed, i + 3)),
        groundY + ry * (0.15 + 0.12 * rnd(seed, i + 9)),
      ];
      d += ` M ${(cx + side * rx * 0.08).toFixed(2)} ${groundY.toFixed(2)} Q ${pt([cx + side * rx * 0.2, groundY + ry * 0.05])} ${pt(tip)}`;
      if (i === 0) anchors.roots = tip;
    }
    ops.push({
      kind: 'path',
      d: d.trim(),
      stroke: 'edge',
      width: 1.6,
      alpha: 0.75,
    });
  }
  const trunk: P[] = [
    [cx - rx * 0.14, groundY],
    [cx - rx * 0.08 + sway, trunkTop],
    [cx + rx * 0.08 + sway, trunkTop],
    [cx + rx * 0.14, groundY],
  ];
  ops.push({
    kind: 'path',
    d: `M ${pt(trunk[0])} L ${pt(trunk[1])} L ${pt(trunk[2])} L ${pt(trunk[3])} Z`,
    fill: 'edge',
    fillAlpha: 0.9,
    stroke: 'edge',
    width: 1.2,
  });
  {
    const lobes: [number, number, number][] = [
      [-0.32, -0.22, 0.4],
      [0.32, -0.22, 0.4],
      [0, -0.55, 0.42],
      [0, -0.2, 0.36],
    ];
    lobes.forEach(([kx, ky, kr], i) => {
      const points: P[] = [];
      const lx = cx + kx * rx + sway * (1 + i * 0.2);
      const ly = cy + ky * ry;
      for (let k = 0; k < 20; k += 1) {
        const th = (k / 20) * Math.PI * 2;
        const r =
          1 +
          0.06 * Math.sin(th * 3 + seed + i) +
          0.03 * Math.sin(t * 0.7 + th * 2);
        points.push([
          lx + Math.cos(th) * rx * kr * r,
          ly + Math.sin(th) * ry * kr * 0.9 * r,
        ]);
      }
      ops.push({
        kind: 'path',
        d: closed(points),
        fill: 'body',
        fillAlpha: 0.9,
        stroke: 'edge',
        width: 1.4,
      });
    });
  }
  const crown: P = [cx + sway, cy - ry * 0.35];
  if (parts.has('fruit')) {
    const points: P[] = [];
    for (let i = 0; i < 6; i += 1)
      points.push([
        crown[0] + (rnd(seed, i + 20) - 0.5) * rx * 1.1,
        crown[1] + (rnd(seed, i + 40) - 0.4) * ry * 0.6,
      ]);
    ops.push({
      kind: 'dots',
      points,
      r: Math.max(2, Math.min(rx, ry) * 0.06),
      fill: 'warm',
      alpha: 0.95,
    });
    anchors.fruit = points[0];
  }
  if (parts.has('flowers')) {
    const points: P[] = [];
    for (let i = 0; i < 9; i += 1)
      points.push([
        crown[0] + (rnd(seed, i + 60) - 0.5) * rx * 1.2,
        crown[1] + (rnd(seed, i + 80) - 0.5) * ry * 0.7,
      ]);
    ops.push({
      kind: 'dots',
      points,
      r: Math.max(1.5, Math.min(rx, ry) * 0.04),
      fill: 'accent',
      alpha: 0.9,
    });
    anchors.flowers = points[0];
  }
  anchors.crown = crown;
  anchors.leaves = crown;
  anchors.trunk = [cx, (groundY + trunkTop) / 2];
  anchors.edge = [cx, cy - ry * 0.95];
}
