// Generated by easyread/scripts/visual-living.mjs. Do not edit; edit the client's copy.
/**
 * Built figures: the drawings no icon set has.
 *
 * Each outline is a recipe, not a picture: a few numbers make a cell, a
 * river system, a fly with beating wings or a cow that walks, and the
 * same recipe serves every thing of that shape. The output is a list of
 * draw operations, so one figure can be painted on canvas while it
 * moves or written as SVG while it sits still.
 */
import {
  birdFigure,
  fishFigure,
  insectFigure,
  personFigure,
  quadrupedFigure,
  segmentedFigure,
} from './figures-creatures';
import {
  blobOutline,
  bodyOutline,
  branchFigure,
  fieldFigure,
  latticeFigure,
  layersFigure,
  skin,
  terrainFigure,
  vesselFigure,
} from './figures-organic';
import {
  pace,
  type FigureDrawing,
  type FigureOp,
  type FigureSpec,
  type Frame,
} from './figures-ops';
import { plantFigure, treeFigure } from './figures-plants';

export type {
  FigureDrawing,
  FigureOp,
  FigureRole,
  FigureSpec,
} from './figures-ops';

/**
 * A figure at a point in its box, at a moment. Nothing here reads the
 * clock except through `t`, so the same moment always draws the same.
 */
export function buildFigure(
  element: FigureSpec,
  ms: number,
  reduced = false,
): FigureDrawing {
  const t = reduced ? 0 : (ms / 1000) * pace(element.manner);
  const f: Frame = {
    cx: element.x,
    cy: element.y,
    rx: (element.w / 2) * 0.94,
    ry: (element.h / 2) * 0.94,
    t,
    seed: (element.seed % 97) / 7,
    parts: new Set(element.parts),
    manner: element.manner,
  };
  const ops: FigureOp[] = [];
  const anchors: Record<string, [number, number]> = { centre: [f.cx, f.cy] };
  switch (element.outline) {
    case 'body':
      skin(f, (scale) => bodyOutline(f, scale), ops, anchors);
      break;
    case 'branch':
      branchFigure(f, ops, anchors);
      break;
    case 'layers':
      layersFigure(f, ops, anchors);
      break;
    case 'lattice':
      latticeFigure(f, ops, anchors);
      break;
    case 'vessel':
      vesselFigure(f, ops, anchors);
      break;
    case 'terrain':
      terrainFigure(f, ops, anchors);
      break;
    case 'field':
      fieldFigure(f, ops, anchors);
      break;
    case 'insect':
      insectFigure(f, ops, anchors);
      break;
    case 'fish':
      fishFigure(f, ops, anchors);
      break;
    case 'bird':
      birdFigure(f, ops, anchors);
      break;
    case 'quadruped':
      quadrupedFigure(f, ops, anchors);
      break;
    case 'segmented':
      segmentedFigure(f, ops, anchors);
      break;
    case 'person':
      personFigure(f, ops, anchors);
      break;
    case 'plant':
      plantFigure(f, ops, anchors);
      break;
    case 'tree':
      treeFigure(f, ops, anchors);
      break;
    default:
      skin(f, (scale) => blobOutline(f, scale), ops, anchors);
  }
  return { ops, anchors };
}
