// Generated by easyread/scripts/visual-living.mjs. Do not edit; edit the client's copy.
/**
 * A pipeline: items enter at a rate and pass through stages in order,
 * each stage taking its time and holding one item. A slow stage backs
 * the others up behind it, and the pile before it is the lesson.
 */
import type { FigureOp } from './figures-ops';
import {
  arrivals,
  dots,
  ease,
  lerp,
  line,
  rect,
  type Anchors,
  type Machine,
} from './mechanisms-shared';

const TRAVEL_S = 0.35;

export function pipelineMechanism(
  m: Machine,
  ops: FigureOp[],
  anchors: Anchors,
): void {
  const { left, top, w, h, t, seed } = m;
  const n = Math.max(2, Math.min(6, Math.round(m.params.stages ?? 4)));
  const slow = Math.max(1, Math.min(n, Math.round(m.params.slow ?? 3))) - 1;
  const rate = Math.max(0.2, m.params.rate ?? 1);
  const bottleneck = m.stage === 'bottleneck';
  const delay = (k: number) => (bottleneck ? (k === slow ? 2.6 : 0.7) : 0.9);
  const came = arrivals(rate, t, seed, 0.2);
  // Each item through each stage: it waits for the stage to be free.
  const free = Array.from({ length: n }, () => 0);
  const plan = came.map((at) => {
    const enter: number[] = [];
    const done: number[] = [];
    let ready = at;
    for (let k = 0; k < n; k += 1) {
      const start = Math.max(ready + TRAVEL_S, free[k]);
      enter.push(start);
      done.push(start + delay(k));
      free[k] = done[k];
      ready = done[k];
    }
    return { at, enter, done };
  });
  const bw = Math.min((w * 0.84) / n - w * 0.04, h * 0.5);
  const bh = h * 0.42;
  const y = top + h * 0.45;
  const xs = Array.from(
    { length: n },
    (_, k) => left + w * 0.08 + ((k + 0.5) * w * 0.84) / n,
  );
  const entry = left + w * 0.02;
  const exit = left + w * 0.98;
  const r = Math.max(2.5, Math.min(bw, bh) * 0.16);
  line(
    ops,
    [
      [entry, y],
      [exit, y],
    ],
    1.2,
    'edge',
    0.3,
  );
  xs.forEach((x, k) => {
    ops.push({
      kind: 'path',
      d: rect(x - bw / 2, y - bh / 2, bw, bh, 5),
      fill: bottleneck && k === slow ? 'warm' : 'body',
      fillAlpha: bottleneck && k === slow ? 0.3 : 0.22,
      stroke: bottleneck && k === slow ? 'warm' : 'edge',
      width: 1.6,
    });
    anchors[`stage${k + 1}`] = [x, y - bh / 2];
  });
  const waitingAt = Array.from({ length: n }, () => 0);
  for (const p of plan) {
    for (let k = 0; k < n; k += 1) {
      const from = k === 0 ? p.at : p.done[k - 1];
      if (t < from) break;
      if (t < p.enter[k]) {
        // On its way, or waiting before the stage.
        const u = (t - from) / TRAVEL_S;
        const startX = k === 0 ? entry : xs[k - 1] + bw / 2;
        const waitX = xs[k] - bw / 2 - r * 1.4;
        if (u < 1) {
          dots(ops, [[lerp(startX, waitX, ease(u)), y]], r, 'body', 0.95);
        } else {
          const slot = waitingAt[k];
          waitingAt[k] += 1;
          if (slot < 6)
            dots(
              ops,
              [[waitX - slot * r * 2.3, y - (slot % 2) * r * 0.9]],
              r,
              bottleneck && k === slow ? 'warm' : 'body',
              0.95,
            );
        }
        break;
      }
      if (t < p.done[k]) {
        // Inside the stage, with its progress under the box.
        const done = (t - p.enter[k]) / (p.done[k] - p.enter[k]);
        dots(ops, [[xs[k], y]], r, 'accent', 1);
        line(
          ops,
          [
            [xs[k] - bw * 0.4, y + bh / 2 + 5],
            [xs[k] - bw * 0.4 + bw * 0.8 * done, y + bh / 2 + 5],
          ],
          2.4,
          'accent',
          0.9,
        );
        break;
      }
      if (k === n - 1) {
        const u = (t - p.done[k]) / 0.45;
        if (u < 1)
          dots(
            ops,
            [[lerp(xs[k] + bw / 2, exit, ease(u)), y]],
            r,
            'accent',
            1 - u * 0.7,
          );
      }
    }
  }
  anchors.entry = [entry, y];
  anchors.exit = [exit, y];
  anchors.bottleneck = [xs[slow], y + bh / 2];
  anchors.centre = [left + w / 2, y];
}
