// Generated by easyread/scripts/visual-living.mjs. Do not edit; edit the client's copy.
/**
 * Mechanisms: the moving pictures a page about a process needs. Each
 * kind is a small machine run from a few numbers; the stage running and
 * the seconds since it began are the only clock.
 */
import type { FigureDrawing, FigureOp } from './figures-ops';
import { balanceMechanism } from './mechanisms-balance';
import { bucketMechanism } from './mechanisms-bucket';
import { cycleMechanism } from './mechanisms-cycle';
import { pipelineMechanism } from './mechanisms-pipeline';
import { pumpMechanism } from './mechanisms-pump';
import { queueMechanism } from './mechanisms-queue';
import type { Machine, MechanismSpec } from './mechanisms-shared';
import { spreadMechanism } from './mechanisms-spread';

export type { MechanismSpec } from './mechanisms-shared';

/**
 * A mechanism at a moment: the stage by index into its stages, and the
 * time since that stage began. Reduced motion draws the stage's first
 * frame.
 */
export function buildMechanism(
  element: MechanismSpec,
  stageIndex: number,
  sinceMs: number,
  reduced = false,
): FigureDrawing {
  const stage =
    element.stages[
      Math.max(0, Math.min(element.stages.length - 1, stageIndex))
    ] ?? '';
  const m: Machine = {
    left: element.x - element.w / 2,
    top: element.y - element.h / 2,
    w: element.w,
    h: element.h,
    cx: element.x,
    cy: element.y,
    params: element.params,
    stage,
    t: reduced ? 0.01 : Math.max(0, sinceMs) / 1000,
    seed: element.seed,
  };
  const ops: FigureOp[] = [];
  const anchors: Record<string, [number, number]> = {};
  switch (element.kind) {
    case 'queue':
      queueMechanism(m, ops, anchors);
      break;
    case 'pipeline':
      pipelineMechanism(m, ops, anchors);
      break;
    case 'cycle':
      cycleMechanism(m, ops, anchors);
      break;
    case 'balance':
      balanceMechanism(m, ops, anchors);
      break;
    case 'spread':
      spreadMechanism(m, ops, anchors);
      break;
    case 'pump':
      pumpMechanism(m, ops, anchors);
      break;
    default:
      bucketMechanism(m, ops, anchors);
  }
  return { ops, anchors };
}
