// Generated by easyread/scripts/visual-living.mjs. Do not edit; edit the client's copy.
/**
 * A pump: a chamber with a valve each side. It swells as it fills from
 * the inlet, then squeezes and the outlet valve lets it out.
 */
import { ellipse, rnd, type FigureOp } from './figures-ops';
import {
  dots,
  line,
  type Anchors,
  type Machine,
  type P,
} from './mechanisms-shared';

export function pumpMechanism(
  m: Machine,
  ops: FigureOp[],
  anchors: Anchors,
): void {
  const { cx, cy, left, w, h, t, seed } = m;
  const beats = Math.max(12, m.params.beats ?? 60);
  const period = 60 / beats;
  const cycle = (t / period) % 1;
  const phase =
    m.stage === 'fill'
      ? Math.min(0.5, t / period)
      : m.stage === 'squeeze'
        ? 0.5 + Math.min(0.5, t / period)
        : cycle;
  const filling = phase < 0.5;
  const swell = filling ? phase / 0.5 : 1 - (phase - 0.5) / 0.5;
  const rx = w * 0.17 * (0.86 + 0.2 * swell);
  const ry = h * 0.28 * (0.86 + 0.2 * swell);
  const pipe = h * 0.16;
  const inX = cx - rx;
  const outX = cx + rx;
  // The pipes, then the chamber over their ends.
  for (const [x0, x1] of [
    [left + w * 0.04, inX],
    [outX, left + w * 0.96],
  ]) {
    line(
      ops,
      [
        [x0, cy - pipe / 2],
        [x1, cy - pipe / 2],
      ],
      2,
      'edge',
    );
    line(
      ops,
      [
        [x0, cy + pipe / 2],
        [x1, cy + pipe / 2],
      ],
      2,
      'edge',
    );
  }
  ops.push({
    kind: 'path',
    d: ellipse(cx, cy, rx, ry),
    fill: 'body',
    fillAlpha: 0.55 + 0.3 * swell,
    stroke: 'edge',
    width: 2.2,
  });
  // Valves: a flap that swings open with the flow through it.
  const flap = (x: number, open: number, dir: number) => {
    const a = -Math.PI / 2 + dir * open * 1.1;
    const tip: P = [
      x + Math.cos(a) * pipe * 0.95,
      cy + pipe / 2 + Math.sin(a) * pipe * 0.95,
    ];
    line(ops, [[x, cy + pipe / 2], tip], 2.4, 'ink', 0.85);
  };
  flap(inX - pipe * 0.2, filling ? 1 : 0, 1);
  flap(outX + pipe * 0.2, filling ? 0 : 1, 1);
  // What flows: in through the inlet while it fills, out through the outlet while it squeezes.
  const flow: P[] = [];
  for (let i = 0; i < 6; i += 1) {
    const u = (t * 0.8 + rnd(seed, i)) % 1;
    if (filling)
      flow.push([
        left + w * 0.06 + u * (inX - pipe * 0.4 - left - w * 0.06),
        cy + (rnd(seed, i + 9) - 0.5) * pipe * 0.5,
      ]);
    else
      flow.push([
        outX + pipe * 0.4 + u * (left + w * 0.94 - outX - pipe * 0.4),
        cy + (rnd(seed, i + 9) - 0.5) * pipe * 0.5,
      ]);
  }
  dots(ops, flow, Math.max(2, pipe * 0.14), 'accent', 0.9);
  const inside: P[] = [];
  for (let i = 0; i < 5; i += 1) {
    const a = rnd(seed, i + 20) * Math.PI * 2 + t * 0.4;
    const k = 0.25 + 0.5 * rnd(seed, i + 30);
    inside.push([cx + Math.cos(a) * rx * k, cy + Math.sin(a) * ry * k]);
  }
  dots(ops, inside, Math.max(2, pipe * 0.13), 'accent', 0.75);
  anchors.inlet = [inX - pipe * 0.4, cy - pipe / 2];
  anchors.outlet = [outX + pipe * 0.4, cy - pipe / 2];
  anchors.chamber = [cx, cy - ry];
  anchors.valve = [inX - pipe * 0.2, cy + pipe / 2];
  anchors.centre = [cx, cy];
}
