// Generated by easyread/scripts/visual-living.mjs. Do not edit; edit the client's copy.
/**
 * A token bucket: tokens drip in from a tap at a rate, the bucket holds
 * a capacity and spills the rest, and requests arriving along the lane
 * below take their tokens at the outlet or bounce off when there are
 * none.
 */
import type { FigureOp } from './figures-ops';
import {
  arrivals,
  circle,
  dots,
  ease,
  lerp,
  line,
  poly,
  rect,
  type Anchors,
  type Machine,
  type P,
} from './mechanisms-shared';

const FALL_S = 0.45;
const APPROACH_S = 0.9;
const LEAVE_S = 0.7;
const BOUNCE_S = 0.5;

interface Regime {
  rate: number;
  requests: number;
  tokens0: number;
}

function regime(m: Machine): Regime {
  const capacity = m.params.capacity ?? 8;
  const rate = m.params.rate ?? 2;
  const requests = m.params.requests ?? 2;
  switch (m.stage) {
    case 'serve':
      return { rate, requests, tokens0: capacity };
    case 'burst':
      return { rate, requests: requests * 3, tokens0: capacity };
    case 'refuse':
      return { rate: 0, requests: Math.max(1, requests) * 2, tokens0: 0 };
    default:
      return { rate, requests: 0, tokens0: 0 };
  }
}

export function bucketMechanism(
  m: Machine,
  ops: FigureOp[],
  anchors: Anchors,
): void {
  const { left, top, w, h, t, seed } = m;
  const capacity = Math.max(2, Math.round(m.params.capacity ?? 8));
  const perRequest = Math.max(1, Math.round(m.params.perRequest ?? 1));
  const { rate, requests, tokens0 } = regime(m);
  // Geometry: the tap over the bucket, the bucket in the middle, the lane below.
  const bx = left + w * 0.5;
  const rimY = top + h * 0.3;
  const bottomY = top + h * 0.78;
  const halfTop = w * 0.21;
  const halfBottom = w * 0.17;
  const tapX = bx - w * 0.06;
  const tapY = top + h * 0.1;
  const laneY = top + h * 0.92;
  const outletX = bx + halfBottom + w * 0.06;
  // The schedule up to now: tokens land, requests reach the outlet.
  const drops = arrivals(rate, t, seed, 0.1);
  const asks = arrivals(requests, t, seed + 7, 0.25);
  type Event = { at: number; kind: 'land' | 'ask'; born: number };
  const events: Event[] = [
    ...drops.map((born) => ({
      at: born + FALL_S,
      kind: 'land' as const,
      born,
    })),
    ...asks.map((born) => ({
      at: born + APPROACH_S,
      kind: 'ask' as const,
      born,
    })),
  ]
    .filter((e) => e.at <= t)
    .sort((a, b) => a.at - b.at);
  let tokens = tokens0;
  const spills: number[] = [];
  const served: { at: number; born: number }[] = [];
  const refused: { at: number; born: number }[] = [];
  for (const e of events) {
    if (e.kind === 'land') {
      if (tokens < capacity) tokens += 1;
      else spills.push(e.at);
    } else if (tokens >= perRequest) {
      tokens -= perRequest;
      served.push({ at: e.at, born: e.born });
    } else refused.push({ at: e.at, born: e.born });
  }
  // The bucket and its tap.
  line(
    ops,
    [
      [left + w * 0.28, tapY],
      [tapX, tapY],
      [tapX, tapY + h * 0.06],
    ],
    3,
    'edge',
  );
  ops.push({
    kind: 'path',
    d: rect(left + w * 0.24, tapY - h * 0.05, w * 0.05, h * 0.1, 2),
    fill: 'edge',
    fillAlpha: 0.9,
  });
  const cols = Math.max(3, Math.ceil(Math.sqrt(capacity * 1.7)));
  const rows = Math.ceil(capacity / cols);
  const tokenR = Math.min(
    (halfBottom * 2 * 0.86) / (cols * 2.2),
    ((bottomY - rimY) * 0.9) / (rows * 2.2),
    h * 0.05,
  );
  const slot = (n: number): P => {
    const col = n % cols;
    const row = Math.floor(n / cols);
    const widen =
      1 + (row * (halfTop - halfBottom)) / halfBottom / Math.max(1, rows);
    const span = halfBottom * 2 * 0.86 * widen;
    return [
      bx - span / 2 + ((col + 0.5) * span) / cols,
      bottomY - tokenR * 1.15 - row * tokenR * 2.15,
    ];
  };
  ops.push({
    kind: 'path',
    d: `${poly([
      [bx - halfTop, rimY],
      [bx - halfBottom, bottomY],
      [bx + halfBottom, bottomY],
      [bx + halfTop, rimY],
    ])}`,
    stroke: 'edge',
    width: 2.4,
  });
  ops.push({
    kind: 'path',
    d: poly([
      [bx - halfBottom, bottomY],
      [bx + halfBottom, bottomY],
    ]),
    stroke: 'edge',
    width: 2.4,
  });
  // Tokens held.
  const held: P[] = [];
  for (let n = 0; n < Math.min(tokens, capacity); n += 1) held.push(slot(n));
  dots(ops, held, tokenR, 'accent', 0.95);
  // Tokens falling from the tap, and ones spilling over the rim.
  for (const born of drops) {
    const u = (t - born) / FALL_S;
    if (u < 0 || u >= 1) continue;
    const target = slot(Math.min(capacity - 1, Math.max(0, tokens)));
    const y = lerp(tapY + h * 0.06, target[1], u * u);
    ops.push({
      kind: 'dots',
      points: [[lerp(tapX, target[0], u), y]],
      r: tokenR,
      fill: 'accent',
      alpha: 0.9,
    });
  }
  for (const at of spills) {
    const u = (t - at) / 0.8;
    if (u < 0 || u >= 1) continue;
    const x = bx + halfTop * (0.2 + u * 1.2);
    const y = rimY - tokenR * 2 + u * u * (bottomY - rimY) * 1.3;
    ops.push({
      kind: 'dots',
      points: [[x, y]],
      r: tokenR,
      fill: 'accent',
      alpha: 0.9 * (1 - u),
    });
  }
  // Requests along the lane: approaching, served and leaving, or refused and bouncing.
  const size = Math.max(4, h * 0.06);
  line(
    ops,
    [
      [left + w * 0.02, laneY],
      [left + w * 0.98, laneY],
    ],
    1.2,
    'edge',
    0.35,
  );
  for (const born of asks) {
    const reach = born + APPROACH_S;
    if (t < reach) {
      const u = ease((t - born) / APPROACH_S);
      ops.push({
        kind: 'path',
        d: rect(
          lerp(left + w * 0.03, outletX, u) - size / 2,
          laneY - size / 2,
          size,
          size,
          2,
        ),
        fill: 'body',
        fillAlpha: 0.9,
        stroke: 'edge',
        width: 1,
      });
    }
  }
  for (const s of served) {
    const u = (t - s.at) / LEAVE_S;
    if (u < 0 || u >= 1) continue;
    const x = lerp(outletX, left + w * 0.98, ease(u));
    ops.push({
      kind: 'path',
      d: rect(x - size / 2, laneY - size / 2, size, size, 2),
      fill: 'accent',
      fillAlpha: 0.95,
      stroke: 'edge',
      width: 1,
    });
    for (let k = 0; k < perRequest; k += 1) {
      const ty = lerp(bottomY, laneY - size, Math.min(1, u * 2));
      ops.push({
        kind: 'dots',
        points: [
          [x + (k - (perRequest - 1) / 2) * tokenR * 2.2, ty - tokenR * 1.2],
        ],
        r: tokenR * 0.9,
        fill: 'accent',
        alpha: 0.9,
      });
    }
  }
  for (const r of refused) {
    const u = (t - r.at) / BOUNCE_S;
    if (u < 0 || u >= 1) continue;
    const back = Math.sin(u * Math.PI) * w * 0.08;
    ops.push({
      kind: 'path',
      d: rect(
        outletX - back - size / 2,
        laneY - size / 2 - Math.sin(u * Math.PI) * size * 0.6,
        size,
        size,
        2,
      ),
      fill: 'warm',
      fillAlpha: 0.95,
      stroke: 'edge',
      width: 1,
    });
  }
  // The outlet mark.
  ops.push({
    kind: 'path',
    d: circle([outletX, laneY], size * 0.55),
    stroke: 'edge',
    width: 1.4,
    alpha: 0.7,
  });
  anchors.rim = [bx + halfTop, rimY];
  anchors.tap = [tapX, tapY];
  anchors.outlet = [outletX, laneY];
  anchors.level = held.length ? held[held.length - 1] : [bx, bottomY - tokenR];
  anchors.spill = [bx + halfTop + w * 0.05, rimY + h * 0.1];
  anchors.centre = [bx, (rimY + bottomY) / 2];
}
