// Generated by easyread/scripts/visual-living.mjs. Do not edit; edit the client's copy.
/**
 * A balance: two pans on a beam, weights on each, tipping to the
 * heavier side. A stage adds one weight and the beam settles anew.
 */
import type { FigureOp } from './figures-ops';
import {
  dots,
  ease,
  lerp,
  line,
  poly,
  type Anchors,
  type Machine,
  type P,
} from './mechanisms-shared';

const SETTLE_S = 0.9;
const DROP_S = 0.6;

export function balanceMechanism(
  m: Machine,
  ops: FigureOp[],
  anchors: Anchors,
): void {
  const { cx, top, w, h, t } = m;
  const l0 = Math.max(0, Math.round(m.params.left ?? 3));
  const r0 = Math.max(0, Math.round(m.params.right ?? 3));
  const l1 = m.stage === 'left' ? l0 + 1 : l0;
  const r1 = m.stage === 'right' ? r0 + 1 : r0;
  const tiltOf = (l: number, r: number) =>
    Math.max(-0.3, Math.min(0.3, (r - l) * 0.075));
  const from = tiltOf(l0, r0);
  const to = tiltOf(l1, r1);
  const settled = m.stage === 'even' ? 1 : ease((t - DROP_S * 0.6) / SETTLE_S);
  const tilt = lerp(from, to, settled);
  const pivot: P = [cx, top + h * 0.42];
  const half = w * 0.36;
  const endL: P = [
    pivot[0] - Math.cos(tilt) * half,
    pivot[1] - Math.sin(tilt) * half,
  ];
  const endR: P = [
    pivot[0] + Math.cos(tilt) * half,
    pivot[1] + Math.sin(tilt) * half,
  ];
  const hang = h * 0.2;
  const panW = w * 0.2;
  const pan = (end: P): P => [end[0], end[1] + hang];
  const panL = pan(endL);
  const panR = pan(endR);
  // The stand and the beam.
  ops.push({
    kind: 'path',
    d: `${poly(
      [
        [pivot[0] - w * 0.06, top + h * 0.92],
        [pivot[0], pivot[1]],
        [pivot[0] + w * 0.06, top + h * 0.92],
      ],
      true,
    )}`,
    fill: 'edge',
    fillAlpha: 0.8,
  });
  line(
    ops,
    [
      [pivot[0] - w * 0.16, top + h * 0.92],
      [pivot[0] + w * 0.16, top + h * 0.92],
    ],
    2.4,
    'edge',
  );
  line(ops, [endL, endR], 3, 'edge');
  dots(ops, [pivot], Math.max(3, w * 0.014), 'accent', 1);
  for (const [end, at] of [
    [endL, panL],
    [endR, panR],
  ] as const) {
    line(ops, [end, [at[0] - panW / 2, at[1]]], 1.2, 'edge', 0.8);
    line(ops, [end, [at[0] + panW / 2, at[1]]], 1.2, 'edge', 0.8);
    ops.push({
      kind: 'path',
      d: `M ${(at[0] - panW / 2).toFixed(2)} ${at[1].toFixed(2)} Q ${at[0].toFixed(2)} ${(at[1] + h * 0.09).toFixed(2)} ${(at[0] + panW / 2).toFixed(2)} ${at[1].toFixed(2)}`,
      fill: 'body',
      fillAlpha: 0.5,
      stroke: 'edge',
      width: 1.6,
    });
  }
  // The weights, in rows of three on each pan; a new one drops in.
  const r = Math.max(2.5, Math.min(w * 0.028, h * 0.05));
  const stack = (at: P, count: number, dropping: number) => {
    const points: P[] = [];
    for (let i = 0; i < count; i += 1) {
      const col = i % 3;
      const row = Math.floor(i / 3);
      const p: P = [at[0] + (col - 1) * r * 2.2, at[1] - r - row * r * 1.9];
      if (i === count - 1 && dropping < 1)
        p[1] = lerp(top + h * 0.02, p[1], ease(dropping));
      points.push(p);
    }
    dots(ops, points, r, 'core', 0.95);
  };
  const drop = m.stage === 'even' ? 1 : t / DROP_S;
  stack(panL, l1, m.stage === 'left' ? drop : 1);
  stack(panR, r1, m.stage === 'right' ? drop : 1);
  anchors.left = [panL[0], panL[1] - r * 2];
  anchors.right = [panR[0], panR[1] - r * 2];
  anchors.pivot = pivot;
  anchors.beam = [pivot[0], pivot[1] - 6];
  anchors.centre = pivot;
}
