// Generated by easyread/scripts/visual-living.mjs. Do not edit; edit the client's copy.
/**
 * A spread: one dot in a grid has something, and it passes to
 * neighbours, faster as more have it. Halve the contacts and it slows.
 */
import { rnd, type FigureOp } from './figures-ops';
import { dots, type Anchors, type Machine, type P } from './mechanisms-shared';

const memo = new Map<string, number[]>();

/** When each dot catches it: the shortest path of contact delays from the middle. */
function timesFor(size: number, contacts: number, seed: number): number[] {
  const key = `${size}:${contacts}:${seed}`;
  const known = memo.get(key);
  if (known) return known;
  const n = size * size;
  const times = Array.from({ length: n }, () => Infinity);
  const start = Math.floor(size / 2) * size + Math.floor(size / 2);
  times[start] = 0;
  const done = Array.from({ length: n }, () => false);
  for (let step = 0; step < n; step += 1) {
    let u = -1;
    for (let i = 0; i < n; i += 1)
      if (!done[i] && (u < 0 || times[i] < times[u])) u = i;
    if (u < 0 || times[u] === Infinity) break;
    done[u] = true;
    const r = Math.floor(u / size);
    const c = u % size;
    const near = [
      [r - 1, c],
      [r + 1, c],
      [r, c - 1],
      [r, c + 1],
    ];
    for (const [nr, nc] of near) {
      if (nr < 0 || nc < 0 || nr >= size || nc >= size) continue;
      const v = nr * size + nc;
      const delay = (0.5 + 1.6 * rnd(seed, u * 131 + v)) / contacts;
      if (times[u] + delay < times[v]) times[v] = times[u] + delay;
    }
  }
  memo.set(key, times);
  return times;
}

export function spreadMechanism(
  m: Machine,
  ops: FigureOp[],
  anchors: Anchors,
): void {
  const { cx, cy, w, h, t, seed } = m;
  const size = Math.max(4, Math.min(12, Math.round(m.params.size ?? 8)));
  const given = Math.max(0.5, m.params.contacts ?? 2);
  const contacts = m.stage === 'slow' ? given / 2 : given;
  const times = timesFor(size, contacts, Math.round(seed));
  const spacing = (Math.min(w, h) * 0.86) / size;
  const r = spacing * 0.3;
  const at = (i: number): P => [
    cx + ((i % size) - (size - 1) / 2) * spacing,
    cy + (Math.floor(i / size) - (size - 1) / 2) * spacing,
  ];
  const healthy: P[] = [];
  const caught: { p: P; since: number }[] = [];
  const running = m.stage !== 'start';
  for (let i = 0; i < size * size; i += 1) {
    const when = times[i];
    if ((running && when <= t) || (!running && when === 0))
      caught.push({ p: at(i), since: t - when });
    else healthy.push(at(i));
  }
  dots(ops, healthy, r, 'body', 0.5);
  // A fresh catch pops, then settles.
  const fresh = caught.filter((c) => c.since < 0.35);
  const settled = caught.filter((c) => c.since >= 0.35);
  dots(
    ops,
    settled.map((c) => c.p),
    r,
    'warm',
    0.95,
  );
  for (const c of fresh)
    dots(
      ops,
      [c.p],
      r * (1 + 0.5 * Math.sin((c.since / 0.35) * Math.PI)),
      'warm',
      0.95,
    );
  const first = at(Math.floor(size / 2) * size + Math.floor(size / 2));
  anchors.first = first;
  anchors.edge = at(0);
  anchors.grid = [cx, cy - (size / 2) * spacing];
  anchors.centre = [cx, cy];
}
