// Generated by easyread/scripts/visual-living.mjs. Do not edit; edit the client's copy.
/**
 * A queue: arrivals come in from the left, wait in a line, and a few
 * servers take them in turn. When arrivals outrun the servers the line
 * grows, which is the whole lesson.
 */
import type { FigureOp } from './figures-ops';
import {
  arrivals,
  circle,
  ease,
  lerp,
  line,
  rect,
  type Anchors,
  type Machine,
  type P,
} from './mechanisms-shared';

const ENTER_S = 0.5;
const LEAVE_S = 0.5;

export function queueMechanism(
  m: Machine,
  ops: FigureOp[],
  anchors: Anchors,
): void {
  const { left, top, w, h, t, seed } = m;
  const servers = Math.max(1, Math.min(4, Math.round(m.params.servers ?? 2)));
  const service = Math.max(0.2, m.params.service ?? 1);
  const given = Math.max(0, m.params.arrivals ?? 2);
  const capacity = servers * service;
  const rate =
    m.stage === 'busy'
      ? capacity
      : m.stage === 'overload'
        ? capacity * 1.7
        : Math.min(given, capacity * 0.8);
  const came = arrivals(rate, t, seed, 0.5);
  // First come, first served, by whichever server frees first.
  const free = Array.from({ length: servers }, () => 0);
  const plan = came.map((at) => {
    let which = 0;
    for (let k = 1; k < servers; k += 1) if (free[k] < free[which]) which = k;
    const start = Math.max(at, free[which]);
    const end = start + 1 / service;
    free[which] = end;
    return { at, start, end, which };
  });
  const entry = left + w * 0.05;
  const serverX = left + w * 0.74;
  const exit = left + w * 0.96;
  const mid = top + h * 0.5;
  const box = Math.min(w * 0.13, (h * 0.8) / servers / 1.3);
  const serverY = (k: number) => mid + (k - (servers - 1) / 2) * box * 1.3;
  const r = Math.max(2.5, Math.min(w, h) * 0.035);
  for (let k = 0; k < servers; k += 1)
    ops.push({
      kind: 'path',
      d: rect(serverX - box / 2, serverY(k) - box / 2, box, box, 4),
      fill: 'body',
      fillAlpha: 0.25,
      stroke: 'edge',
      width: 1.6,
    });
  line(
    ops,
    [
      [entry, mid],
      [serverX - box * 0.7, mid],
    ],
    1.2,
    'edge',
    0.3,
  );
  ops.push({
    kind: 'path',
    d: circle([entry, mid], r * 1.4),
    stroke: 'edge',
    width: 1.4,
    alpha: 0.6,
  });
  ops.push({
    kind: 'path',
    d: circle([exit, mid], r * 1.4),
    stroke: 'edge',
    width: 1.4,
    alpha: 0.6,
  });
  // Who waits: every arrival not yet in service, in order.
  const waiting = plan.filter((p) => p.at <= t && t < p.start);
  const front = serverX - box * 0.9;
  waiting.forEach((p, k) => {
    const slot: P = [front - k * r * 2.6, mid];
    const u = ease((t - p.at) / ENTER_S);
    const from: P = [entry, mid];
    const at: P = [lerp(from[0], slot[0], u), lerp(from[1], slot[1], u)];
    if (at[0] > entry - r)
      ops.push({ kind: 'dots', points: [at], r, fill: 'body', alpha: 0.95 });
  });
  // Who is being served: a ring filling round the dot.
  for (const p of plan) {
    if (t < p.start || t >= p.end) continue;
    const c: P = [serverX, serverY(p.which)];
    ops.push({ kind: 'dots', points: [c], r, fill: 'accent', alpha: 1 });
    const done = (t - p.start) / (p.end - p.start);
    const a0 = -Math.PI / 2;
    const a1 = a0 + Math.PI * 2 * done;
    const R = r * 2;
    const large = done > 0.5 ? 1 : 0;
    ops.push({
      kind: 'path',
      d: `M ${(c[0] + Math.cos(a0) * R).toFixed(2)} ${(c[1] + Math.sin(a0) * R).toFixed(2)} A ${R.toFixed(2)} ${R.toFixed(2)} 0 ${large} 1 ${(c[0] + Math.cos(a1) * R).toFixed(2)} ${(c[1] + Math.sin(a1) * R).toFixed(2)}`,
      stroke: 'accent',
      width: 1.6,
      alpha: 0.9,
    });
  }
  // Who has left.
  for (const p of plan) {
    const u = (t - p.end) / LEAVE_S;
    if (u < 0 || u >= 1) continue;
    const from: P = [serverX, serverY(p.which)];
    ops.push({
      kind: 'dots',
      points: [
        [lerp(from[0] + box / 2, exit, ease(u)), lerp(from[1], mid, ease(u))],
      ],
      r,
      fill: 'accent',
      alpha: 1 - u * 0.6,
    });
  }
  anchors.entry = [entry, mid];
  anchors.line = [front - r * 2, mid];
  anchors.servers = [serverX, serverY(0)];
  anchors.exit = [exit, mid];
  anchors.centre = [left + w * 0.45, mid];
}
