// Generated by easyread/scripts/visual-living.mjs. Do not edit; edit the client's copy.
/**
 * A cycle: things circulate round stations on a ring. When one station
 * stops, the things pile up before it; when it opens, the pile clears.
 */
import type { FigureOp } from './figures-ops';
import {
  circle,
  dots,
  rect,
  type Anchors,
  type Machine,
  type P,
} from './mechanisms-shared';

export function cycleMechanism(
  m: Machine,
  ops: FigureOp[],
  anchors: Anchors,
): void {
  const { cx, cy, w, h, t, seed } = m;
  const n = Math.max(2, Math.min(6, Math.round(m.params.stations ?? 4)));
  const speed = Math.max(1, m.params.speed ?? 6);
  const omega = (Math.PI * 2 * speed) / 60;
  const R = Math.min(w, h) * 0.38;
  const size = R * 0.3;
  const count = n * 2;
  const slot = 0.24;
  const stationAngle = (k: number) => -Math.PI / 2 + (k * Math.PI * 2) / n;
  const base = (i: number) =>
    (i * Math.PI * 2) / count + Math.PI / count + (((seed * 13) % 7) / 7) * 0.1;
  // Where each thing stops when station one is blocked: the next time it
  // would reach it, less a slot for each thing already there.
  const caps: number[] = [];
  {
    const reach = Array.from({ length: count }, (_, i) => {
      const b = base(i);
      const target =
        stationAngle(0) +
        Math.PI * 2 * Math.ceil((b - stationAngle(0)) / (Math.PI * 2) + 1e-6);
      return { i, target };
    }).sort((a, b) => a.target - b.target);
    reach.forEach((r, rank) => {
      caps[r.i] = r.target - rank * slot;
    });
  }
  const angle = (i: number): number => {
    const run = base(i) + omega * t;
    if (m.stage === 'block') return Math.min(run, caps[i]);
    if (m.stage === 'resume') return caps[i] + omega * t;
    return run;
  };
  ops.push({
    kind: 'path',
    d: circle([cx, cy], R),
    stroke: 'edge',
    width: 1.6,
    alpha: 0.45,
  });
  for (let k = 0; k < n; k += 1) {
    const a = stationAngle(k);
    const c: P = [cx + Math.cos(a) * R, cy + Math.sin(a) * R];
    const blocked = m.stage === 'block' && k === 0;
    ops.push({
      kind: 'path',
      d: rect(c[0] - size / 2, c[1] - size / 2, size, size, 4),
      fill: blocked ? 'warm' : 'body',
      fillAlpha: blocked ? 0.5 : 0.35,
      stroke: blocked ? 'warm' : 'edge',
      width: 1.6,
    });
    anchors[`station${k + 1}`] = c;
  }
  const points: P[] = [];
  for (let i = 0; i < count; i += 1) {
    const a = angle(i);
    points.push([cx + Math.cos(a) * R, cy + Math.sin(a) * R]);
  }
  dots(ops, points, Math.max(2.5, R * 0.07), 'accent', 0.95);
  anchors.ring = [cx, cy - R];
  anchors.centre = [cx, cy];
}
