// Generated by easyread/scripts/visual-living.mjs. Do not edit; edit the client's copy.
/**
 * What every mechanism is drawn from, and the helpers the machines
 * share. A mechanism runs from the numbers a page gives: its state at
 * any second is derived from an event schedule, never accumulated, so a
 * seek lands true and a reload draws the same frame.
 */
import { pt, rnd, type FigureOp, type FigureRole } from './figures-ops';

export type P = [number, number];
export type Anchors = Record<string, P>;

/** The element as the machines read it. */
export interface MechanismSpec {
  x: number;
  y: number;
  w: number;
  h: number;
  kind: string;
  params: Record<string, number>;
  stages: string[];
  seed: number;
}

/** One machine's frame: its box, the stage running, and the seconds since that stage began. */
export interface Machine {
  left: number;
  top: number;
  w: number;
  h: number;
  cx: number;
  cy: number;
  params: Record<string, number>;
  stage: string;
  t: number;
  seed: number;
}

export const ease = (u: number) => {
  const k = Math.max(0, Math.min(1, u));
  return k * k * (3 - 2 * k);
};

export const lerp = (a: number, b: number, u: number) => a + (b - a) * u;

export const circle = (c: P, r: number) =>
  `M ${(c[0] - r).toFixed(2)} ${c[1].toFixed(2)} a ${r.toFixed(2)} ${r.toFixed(2)} 0 1 0 ${(r * 2).toFixed(2)} 0 a ${r.toFixed(2)} ${r.toFixed(2)} 0 1 0 ${(-r * 2).toFixed(2)} 0`;

export const rect = (x: number, y: number, w: number, h: number, r = 0) =>
  r
    ? `M ${(x + r).toFixed(2)} ${y.toFixed(2)} H ${(x + w - r).toFixed(2)} Q ${(x + w).toFixed(2)} ${y.toFixed(2)} ${(x + w).toFixed(2)} ${(y + r).toFixed(2)} V ${(y + h - r).toFixed(2)} Q ${(x + w).toFixed(2)} ${(y + h).toFixed(2)} ${(x + w - r).toFixed(2)} ${(y + h).toFixed(2)} H ${(x + r).toFixed(2)} Q ${x.toFixed(2)} ${(y + h).toFixed(2)} ${x.toFixed(2)} ${(y + h - r).toFixed(2)} V ${(y + r).toFixed(2)} Q ${x.toFixed(2)} ${y.toFixed(2)} ${(x + r).toFixed(2)} ${y.toFixed(2)} Z`
    : `M ${x.toFixed(2)} ${y.toFixed(2)} h ${w.toFixed(2)} v ${h.toFixed(2)} h ${(-w).toFixed(2)} Z`;

export const poly = (points: P[], close = false) =>
  `M ${pt(points[0])} ${points
    .slice(1)
    .map((p) => `L ${pt(p)}`)
    .join(' ')}${close ? ' Z' : ''}`;

export const line = (
  ops: FigureOp[],
  points: P[],
  width: number,
  stroke: FigureRole = 'edge',
  alpha = 1,
) => ops.push({ kind: 'path', d: poly(points), stroke, width, alpha });

export const dots = (
  ops: FigureOp[],
  points: P[],
  r: number,
  fill: FigureRole,
  alpha = 1,
) => {
  if (points.length) ops.push({ kind: 'dots', points, r, fill, alpha });
};

/** Times at which things arrive, at a rate a second, each a little early or late by the seed. */
export function arrivals(
  rate: number,
  until: number,
  seed: number,
  jitter = 0.3,
): number[] {
  const out: number[] = [];
  if (rate <= 0) return out;
  for (let i = 0; i < 4000; i += 1) {
    const at = (i + 0.5 + (rnd(seed, i) - 0.5) * jitter) / rate;
    if (at > until) break;
    out.push(at);
  }
  return out;
}
