// Generated by easyread/scripts/visual-living.mjs. Do not edit; edit the client's copy.
export const MOTIONS = [
  'travel',
  'bounce',
  'hover',
  'spin',
  'shake',
  'along',
  'grow',
] as const;
export type MotionName = (typeof MOTIONS)[number];

/** What each motion looks like and when it fits, as the director reads it. */
export const MOTION_MEANINGS: Record<
  MotionName,
  { what: string; when: string }
> = {
  travel: {
    what: 'comes in from the left to its place, then rides a little',
    when: 'a thing that goes somewhere or arrives',
  },
  bounce: {
    what: 'lands and bounces in place',
    when: 'a thing that drops in or is dropped',
  },
  hover: {
    what: 'is held in the air, bobbing',
    when: 'a thing that waits, floats or is weighed',
  },
  spin: {
    what: 'turns on its centre',
    when: 'a round thing only: a gear, a globe, a clock, a coin, a wheel, a cycle',
  },
  shake: {
    what: 'shakes once and stops',
    when: 'alarm, failure or a warning only',
  },
  along: {
    what: "slides from its place to the next thing's place and stays there",
    when: 'a thing that passes from one step or party to the next; in a scene, to the picture after it',
  },
  grow: {
    what: 'grows from small to its full size and holds',
    when: 'a quantity or a thing that rises, builds up or accrues',
  },
};

/** Motions that keep going until told to settle; the rest end on their own. */
export const LASTING: ReadonlySet<string> = new Set([
  'travel',
  'bounce',
  'hover',
  'spin',
]);

export interface MotionPose {
  dx: number;
  dy: number;
  rotate: number;
  scale: number;
}
export const AT_REST: MotionPose = { dx: 0, dy: 0, rotate: 0, scale: 1 };

const clamp = (u: number) => Math.max(0, Math.min(1, u));
const easeOut = (u: number) => 1 - Math.pow(1 - clamp(u), 3);
const easeInOut = (u: number) => {
  const v = clamp(u);
  return v < 0.5 ? 4 * v * v * v : 1 - Math.pow(-2 * v + 2, 3) / 2;
};
/** How much of a lasting motion is left `t` seconds in: all of it until it settles, none 0.6 s after. */
const remaining = (t: number, settle: number | null) =>
  settle === null || t <= settle ? 1 : 1 - easeOut((t - settle) / 0.6);

/**
 * The pose `t` seconds after the thing was shown. `settle` is when its
 * sentence ended, in the same seconds, after which a lasting motion eases
 * to rest; `to` is where an `along` thing goes, relative to its own place.
 */
export function motionPose(
  motion: string,
  t: number,
  settle: number | null = null,
  to: { dx: number; dy: number } | null = null,
): MotionPose {
  const s = Math.max(0, t);
  switch (motion) {
    case 'travel': {
      const u = easeOut(s / 1.5);
      const ride =
        s >= 1.5 ? Math.sin((s - 1.5) * 2) * 2 * remaining(s, settle) : 0;
      return { ...AT_REST, dx: (u - 1) * 70, dy: ride };
    }
    case 'bounce':
      return {
        ...AT_REST,
        dy: -Math.abs(Math.sin(s * 5)) * 5 * remaining(s, settle),
      };
    case 'hover':
      return { ...AT_REST, dy: Math.sin(s * 2.2) * 3 * remaining(s, settle) };
    case 'spin': {
      // Turns until told to settle, then eases to the next full turn.
      const base = 60 * Math.min(s, settle ?? s);
      if (settle === null || s <= settle)
        return { ...AT_REST, rotate: base % 360 };
      const whole = Math.ceil(base / 360) * 360;
      return {
        ...AT_REST,
        rotate: (base + (whole - base) * easeOut((s - settle) / 0.8)) % 360,
      };
    }
    case 'shake':
      return s < 1
        ? { ...AT_REST, dx: Math.sin(s * 40) * 2 * (1 - s) }
        : AT_REST;
    case 'along': {
      if (!to) return motionPose('travel', t, settle);
      const far = Math.hypot(to.dx, to.dy);
      const u = easeInOut(s / Math.max(1, far / 120));
      return { ...AT_REST, dx: to.dx * u, dy: to.dy * u };
    }
    case 'grow': {
      const u = easeOut(s / 1.2);
      // A little over, then back: the growth is felt.
      const over = s < 1.2 ? Math.sin(u * Math.PI) * 0.08 : 0;
      return { ...AT_REST, scale: 0.45 + 0.55 * u + over };
    }
    default:
      return AT_REST;
  }
}

/** Whether a pose is the thing at rest. */
export function atRest(pose: MotionPose): boolean {
  return (
    pose.dx === 0 && pose.dy === 0 && pose.rotate === 0 && pose.scale === 1
  );
}

/** The pose as a CSS transform about the thing's own centre. */
export function motionTransform(pose: MotionPose): string | undefined {
  if (atRest(pose)) return undefined;
  return `translate(${pose.dx.toFixed(2)}px, ${pose.dy.toFixed(2)}px) rotate(${pose.rotate.toFixed(2)}deg) scale(${pose.scale.toFixed(3)})`;
}
