// Generated by easyread/scripts/visual-living.mjs. Do not edit; edit the client's copy.
export interface Preset {
  /** The filled silhouette: one or more closed subpaths on the unit square. */
  body: string;
  /** Lines drawn over the body in the same colour, darker: veins, crosses, rims. */
  detail?: string;
  /** Width over height, so the box keeps the drawing's proportions. */
  aspect: number;
  /** The words a chapter would use for this thing, so the server can find it. */
  tags?: string;
  /**
   * The field whose own vocabulary this belongs to. A field's term is
   * answered from its own pack or by words, never by a drawing from the
   * general library that merely does the same job: a glomerulus is not
   * a funnel.
   */
  field?: Field;
  /**
   * The parts a callout can point at, each with where on the unit
   * square its leader line meets, and the ink that belongs to it alone.
   * A drawing of an organ is no use to a page about that organ unless
   * its parts can be named one at a time.
   */
  parts?: Record<string, PresetPart>;
}

/** The fields whose own terms are answered from their own pack. */
export type Field =
  | 'medicine'
  | 'agriculture'
  | 'law'
  | 'engineering'
  | 'finance'
  | 'computing'
  | 'science';

/** One named part of a drawing. */
export interface PresetPart {
  /** Where a leader line meets this part, on the unit square. */
  at: [number, number];
  /** Ink that is this part and no other: drawn with the body, lit on its own when named. */
  fill?: string;
  /** Lines that are this part: drawn with the detail, lit on its own when named. */
  stroke?: string;
}

import { AGRICULTURE } from './packs/agriculture';
import { MEDICINE } from './packs/medicine';

/** The field packs, each a field's own vocabulary drawn for it. */
export const PACKS: Record<string, Record<string, Preset>> = {
  medicine: MEDICINE,
  agriculture: AGRICULTURE,
};

/**
 * Which field a drawing belongs to. A field's own term is answered from
 * that field's pack or by words, and never by a drawing from the general
 * library that merely does the same job: a glomerulus is not a funnel.
 */
export const FIELD_OF: Record<string, Field> = Object.fromEntries(
  Object.values(PACKS).flatMap((pack) =>
    Object.entries(pack)
      .filter(([, preset]) => preset.field)
      .map(([name, preset]) => [name, preset.field as Field]),
  ),
);

const HAND: Record<string, Preset> = {
  // ── nature and general ──
  leaf: {
    body: 'M0 0.7 C0.11 0.13 0.73 0 1 0.33 C0.88 0.85 0.29 1 0 0.7 Z',
    detail: 'M0.04 0.67 C0.32 0.54 0.67 0.4 0.96 0.34',
    aspect: 1.12,
  },
  sun: {
    body: 'M0.5 0.28 A0.22 0.22 0 1 0 0.5 0.72 A0.22 0.22 0 1 0 0.5 0.28 Z',
    detail:
      'M0.5 0.04 V0.16 M0.5 0.84 V0.96 M0.04 0.5 H0.16 M0.84 0.5 H0.96 M0.17 0.17 L0.26 0.26 M0.74 0.74 L0.83 0.83 M0.17 0.83 L0.26 0.74 M0.74 0.26 L0.83 0.17',
    aspect: 1,
  },
  cloud: {
    body: 'M0.24 0.82 A0.17 0.17 0 0 1 0.2 0.49 A0.22 0.22 0 0 1 0.62 0.38 A0.16 0.16 0 0 1 0.78 0.82 Z',
    aspect: 1.5,
  },
  drop: {
    body: 'M0.5 0.02 C0.5 0.22 0.14 0.44 0.14 0.66 A0.36 0.36 0 0 0 0.86 0.66 C0.86 0.44 0.5 0.22 0.5 0.02 Z',
    detail: 'M0.32 0.7 A0.18 0.18 0 0 0 0.44 0.86',
    aspect: 0.72,
  },
  globe: {
    body: 'M0.5 0.06 A0.44 0.44 0 1 0 0.5 0.94 A0.44 0.44 0 1 0 0.5 0.06 Z',
    detail:
      'M0.06 0.5 H0.94 M0.5 0.06 C0.72 0.3 0.72 0.7 0.5 0.94 M0.5 0.06 C0.28 0.3 0.28 0.7 0.5 0.94 M0.14 0.3 H0.86 M0.14 0.7 H0.86',
    aspect: 1,
  },
  star: {
    body: 'M0.5 0.04 L0.62 0.36 L0.96 0.38 L0.7 0.6 L0.78 0.94 L0.5 0.76 L0.22 0.94 L0.3 0.6 L0.04 0.38 L0.38 0.36 Z',
    aspect: 1,
  },
  shield: {
    body: 'M0.5 0.04 L0.9 0.18 V0.5 C0.9 0.74 0.72 0.9 0.5 0.96 C0.28 0.9 0.1 0.74 0.1 0.5 V0.18 Z',
    detail: 'M0.34 0.5 L0.46 0.62 L0.68 0.38',
    aspect: 0.85,
  },
  bulb: {
    body: 'M0.5 0.04 A0.3 0.3 0 0 0 0.3 0.56 C0.36 0.62 0.38 0.68 0.38 0.74 H0.62 C0.62 0.68 0.64 0.62 0.7 0.56 A0.3 0.3 0 0 0 0.5 0.04 Z M0.38 0.8 H0.62 V0.9 H0.38 Z',
    detail: 'M0.42 0.74 V0.55 M0.58 0.74 V0.55',
    aspect: 0.7,
  },
  warning: {
    body: 'M0.5 0.06 L0.96 0.9 H0.04 Z',
    detail: 'M0.5 0.36 V0.62 M0.5 0.72 V0.78',
    aspect: 1.1,
  },
  check: {
    body: 'M0.5 0.04 A0.46 0.46 0 1 0 0.5 0.96 A0.46 0.46 0 1 0 0.5 0.04 Z',
    detail: 'M0.28 0.52 L0.44 0.68 L0.74 0.36',
    aspect: 1,
  },
  question: {
    body: 'M0.5 0.04 A0.46 0.46 0 1 0 0.5 0.96 A0.46 0.46 0 1 0 0.5 0.04 Z',
    detail:
      'M0.36 0.4 A0.14 0.14 0 1 1 0.56 0.54 C0.5 0.58 0.5 0.62 0.5 0.66 M0.5 0.76 V0.78',
    aspect: 1,
  },
  gear: {
    body: 'M0.44 0.02 H0.56 L0.6 0.14 L0.72 0.18 L0.82 0.1 L0.9 0.18 L0.82 0.28 L0.86 0.4 L0.98 0.44 V0.56 L0.86 0.6 L0.82 0.72 L0.9 0.82 L0.82 0.9 L0.72 0.82 L0.6 0.86 L0.56 0.98 H0.44 L0.4 0.86 L0.28 0.82 L0.18 0.9 L0.1 0.82 L0.18 0.72 L0.14 0.6 L0.02 0.56 V0.44 L0.14 0.4 L0.18 0.28 L0.1 0.18 L0.18 0.1 L0.28 0.18 L0.4 0.14 Z M0.5 0.36 A0.14 0.14 0 1 0 0.5 0.64 A0.14 0.14 0 1 0 0.5 0.36 Z',
    aspect: 1,
  },
  clock: {
    body: 'M0.5 0.04 A0.46 0.46 0 1 0 0.5 0.96 A0.46 0.46 0 1 0 0.5 0.04 Z',
    detail: 'M0.5 0.2 V0.5 L0.7 0.62',
    aspect: 1,
  },
  book: {
    body: 'M0.06 0.12 H0.44 A0.06 0.06 0 0 1 0.5 0.18 V0.9 A0.06 0.06 0 0 0 0.44 0.84 H0.06 Z M0.94 0.12 H0.56 A0.06 0.06 0 0 0 0.5 0.18 V0.9 A0.06 0.06 0 0 1 0.56 0.84 H0.94 Z',
    detail: 'M0.14 0.3 H0.4 M0.14 0.44 H0.4 M0.6 0.3 H0.86 M0.6 0.44 H0.86',
    aspect: 1.2,
  },
  arrows: {
    body: 'M0.08 0.34 H0.66 V0.18 L0.96 0.42 L0.66 0.66 V0.5 H0.08 Z M0.92 0.66 H0.34 V0.5 L0.04 0.74 L0.34 0.98 V0.82 H0.92 Z',
    aspect: 1.2,
  },
  document: {
    body: 'M0.14 0.02 H0.64 L0.86 0.24 V0.98 H0.14 Z',
    detail:
      'M0.64 0.02 V0.24 H0.86 M0.26 0.44 H0.74 M0.26 0.58 H0.74 M0.26 0.72 H0.6',
    aspect: 0.75,
  },

  // ── people and health ──
  person: {
    body: 'M0.5 0.06 A0.16 0.16 0 1 0 0.5 0.38 A0.16 0.16 0 1 0 0.5 0.06 Z M0.18 0.98 C0.18 0.62 0.3 0.46 0.5 0.46 C0.7 0.46 0.82 0.62 0.82 0.98 Z',
    aspect: 0.7,
  },
  people: {
    body: 'M0.34 0.1 A0.13 0.13 0 1 0 0.34 0.36 A0.13 0.13 0 1 0 0.34 0.1 Z M0.06 0.96 C0.06 0.62 0.16 0.44 0.34 0.44 C0.52 0.44 0.62 0.62 0.62 0.96 Z M0.7 0.2 A0.11 0.11 0 1 0 0.7 0.42 A0.11 0.11 0 1 0 0.7 0.2 Z M0.58 0.96 C0.62 0.64 0.66 0.5 0.72 0.5 C0.86 0.5 0.96 0.68 0.96 0.96 Z',
    aspect: 1.1,
  },
  family: {
    body: 'M0.24 0.08 A0.13 0.13 0 1 0 0.24 0.34 A0.13 0.13 0 1 0 0.24 0.08 Z M0.02 0.96 C0.02 0.6 0.1 0.42 0.24 0.42 C0.38 0.42 0.46 0.6 0.46 0.96 Z M0.76 0.08 A0.13 0.13 0 1 0 0.76 0.34 A0.13 0.13 0 1 0 0.76 0.08 Z M0.54 0.96 C0.54 0.6 0.62 0.42 0.76 0.42 C0.9 0.42 0.98 0.6 0.98 0.96 Z M0.5 0.48 A0.09 0.09 0 1 0 0.5 0.66 A0.09 0.09 0 1 0 0.5 0.48 Z M0.38 0.96 C0.38 0.76 0.42 0.7 0.5 0.7 C0.58 0.7 0.62 0.76 0.62 0.96 Z',
    aspect: 1.3,
  },
  child: {
    body: 'M0.5 0.1 A0.17 0.17 0 1 0 0.5 0.44 A0.17 0.17 0 1 0 0.5 0.1 Z M0.24 0.96 C0.24 0.66 0.34 0.52 0.5 0.52 C0.66 0.52 0.76 0.66 0.76 0.96 Z',
    aspect: 0.75,
  },
  clinic: {
    body: 'M0.08 0.98 V0.4 L0.5 0.08 L0.92 0.4 V0.98 Z',
    detail: 'M0.5 0.44 V0.72 M0.36 0.58 H0.64 M0.42 0.98 V0.82 H0.58 V0.98',
    aspect: 1.05,
  },
  hospital: {
    body: 'M0.06 0.98 V0.3 H0.34 V0.12 H0.66 V0.3 H0.94 V0.98 Z',
    detail:
      'M0.5 0.18 V0.3 M0.44 0.24 H0.56 M0.16 0.44 H0.26 M0.16 0.6 H0.26 M0.74 0.44 H0.84 M0.74 0.6 H0.84 M0.42 0.98 V0.78 H0.58 V0.98',
    aspect: 1.1,
  },
  bed: {
    body: 'M0.04 0.9 V0.36 H0.14 V0.52 H0.96 V0.9 H0.88 V0.72 H0.12 V0.9 Z',
    detail: 'M0.18 0.44 A0.06 0.06 0 1 0 0.3 0.44 A0.06 0.06 0 1 0 0.18 0.44',
    aspect: 1.6,
  },
  pill: {
    body: 'M0.3 0.12 H0.7 A0.2 0.2 0 0 1 0.9 0.32 V0.68 A0.2 0.2 0 0 1 0.7 0.88 H0.3 A0.2 0.2 0 0 1 0.1 0.68 V0.32 A0.2 0.2 0 0 1 0.3 0.12 Z',
    detail: 'M0.1 0.5 H0.9',
    aspect: 1.3,
  },
  syringe: {
    body: 'M0.08 0.44 H0.16 V0.36 H0.68 V0.64 H0.16 V0.56 H0.08 Z M0.68 0.46 H0.86 V0.54 H0.68 Z M0.86 0.48 H0.96 V0.52 H0.86 Z',
    detail: 'M0.28 0.36 V0.64 M0.4 0.36 V0.64 M0.52 0.36 V0.64',
    aspect: 2,
  },
  stethoscope: {
    body: 'M0.2 0.04 C0.2 0.36 0.2 0.5 0.4 0.56 C0.56 0.5 0.56 0.36 0.56 0.04 H0.48 C0.48 0.3 0.48 0.42 0.38 0.46 C0.28 0.42 0.28 0.3 0.28 0.04 Z M0.4 0.56 C0.4 0.76 0.5 0.86 0.68 0.86 C0.8 0.86 0.86 0.8 0.86 0.7 H0.78 C0.78 0.76 0.74 0.78 0.68 0.78 C0.56 0.78 0.48 0.72 0.48 0.56 Z M0.86 0.56 A0.1 0.1 0 1 0 0.86 0.76 A0.1 0.1 0 1 0 0.86 0.56 Z',
    aspect: 1,
  },
  heart: {
    body: 'M0.5 0.94 C0.2 0.72 0.04 0.56 0.04 0.34 A0.22 0.22 0 0 1 0.5 0.24 A0.22 0.22 0 0 1 0.96 0.34 C0.96 0.56 0.8 0.72 0.5 0.94 Z',
    aspect: 1,
  },
  lungs: {
    body: 'M0.46 0.08 H0.54 V0.4 H0.46 Z M0.44 0.34 C0.24 0.3 0.06 0.5 0.06 0.8 C0.06 0.92 0.14 0.96 0.26 0.96 C0.4 0.96 0.44 0.86 0.44 0.7 Z M0.56 0.34 C0.76 0.3 0.94 0.5 0.94 0.8 C0.94 0.92 0.86 0.96 0.74 0.96 C0.6 0.96 0.56 0.86 0.56 0.7 Z',
    aspect: 1,
  },
  tooth: {
    body: 'M0.22 0.1 C0.36 0.02 0.64 0.02 0.78 0.1 C0.96 0.22 0.9 0.48 0.8 0.62 C0.72 0.74 0.72 0.96 0.62 0.96 C0.56 0.96 0.54 0.7 0.5 0.7 C0.46 0.7 0.44 0.96 0.38 0.96 C0.28 0.96 0.28 0.74 0.2 0.62 C0.1 0.48 0.04 0.22 0.22 0.1 Z',
    aspect: 0.9,
  },
  thermometer: {
    body: 'M0.42 0.06 H0.58 V0.62 A0.16 0.16 0 1 1 0.42 0.62 Z',
    detail: 'M0.5 0.28 V0.7 M0.62 0.2 H0.7 M0.62 0.34 H0.7 M0.62 0.48 H0.7',
    aspect: 0.5,
  },
  tap: {
    body: 'M0.1 0.36 H0.3 V0.26 H0.5 V0.36 H0.8 A0.12 0.12 0 0 1 0.92 0.48 V0.56 H0.82 V0.5 A0.04 0.04 0 0 0 0.78 0.46 H0.5 V0.56 H0.3 V0.46 H0.1 Z M0.82 0.62 H0.92 V0.78 A0.05 0.05 0 0 1 0.82 0.78 Z',
    detail: 'M0.4 0.26 V0.14 M0.32 0.14 H0.48',
    aspect: 1.4,
  },
  plate: {
    body: 'M0.5 0.2 A0.44 0.28 0 1 0 0.5 0.76 A0.44 0.28 0 1 0 0.5 0.2 Z',
    detail: 'M0.5 0.32 A0.3 0.18 0 1 0 0.5 0.68 A0.3 0.18 0 1 0 0.5 0.32 Z',
    aspect: 1.6,
  },
  village: {
    body: 'M0.04 0.96 V0.6 L0.22 0.44 L0.4 0.6 V0.96 Z M0.44 0.96 V0.5 L0.64 0.3 L0.84 0.5 V0.96 Z M0.6 0.96 V0.74 H0.68 V0.96 Z',
    detail: 'M0.14 0.96 V0.8 H0.28 V0.96',
    aspect: 1.5,
  },
  ambulance: {
    body: 'M0.04 0.78 V0.34 H0.56 L0.66 0.5 H0.96 V0.78 Z M0.2 0.72 A0.09 0.09 0 1 0 0.38 0.72 A0.09 0.09 0 1 0 0.2 0.72 Z M0.68 0.72 A0.09 0.09 0 1 0 0.86 0.72 A0.09 0.09 0 1 0 0.68 0.72 Z',
    detail: 'M0.3 0.44 V0.66 M0.19 0.55 H0.41 M0.6 0.4 V0.5',
    aspect: 1.7,
  },
  net: {
    body: 'M0.1 0.16 H0.9 V0.9 H0.1 Z',
    detail:
      'M0.3 0.16 V0.9 M0.5 0.16 V0.9 M0.7 0.16 V0.9 M0.1 0.4 H0.9 M0.1 0.64 H0.9',
    aspect: 1.3,
  },
  well: {
    body: 'M0.14 0.62 H0.86 V0.9 H0.14 Z M0.1 0.16 H0.9 V0.26 H0.1 Z',
    detail: 'M0.2 0.26 V0.62 M0.8 0.26 V0.62 M0.5 0.26 V0.5 M0.42 0.5 H0.58',
    aspect: 1,
  },

  // ── computing ──
  server: {
    body: 'M0.1 0.06 H0.9 V0.34 H0.1 Z M0.1 0.4 H0.9 V0.66 H0.1 Z M0.1 0.72 H0.9 V0.98 H0.1 Z',
    detail:
      'M0.2 0.2 H0.4 M0.2 0.53 H0.4 M0.2 0.85 H0.4 M0.76 0.2 H0.8 M0.76 0.53 H0.8 M0.76 0.85 H0.8',
    aspect: 0.9,
  },
  database: {
    body: 'M0.1 0.16 A0.4 0.12 0 0 1 0.9 0.16 V0.84 A0.4 0.12 0 0 1 0.1 0.84 Z',
    detail:
      'M0.1 0.16 A0.4 0.12 0 0 0 0.9 0.16 M0.1 0.5 A0.4 0.12 0 0 0 0.9 0.5',
    aspect: 0.9,
  },
  queue: {
    body: 'M0.04 0.34 H0.96 V0.66 H0.04 Z',
    detail:
      'M0.22 0.34 V0.66 M0.4 0.34 V0.66 M0.58 0.34 V0.66 M0.76 0.34 V0.66',
    aspect: 2.4,
  },
  phone: {
    body: 'M0.28 0.02 H0.72 A0.08 0.08 0 0 1 0.8 0.1 V0.9 A0.08 0.08 0 0 1 0.72 0.98 H0.28 A0.08 0.08 0 0 1 0.2 0.9 V0.1 A0.08 0.08 0 0 1 0.28 0.02 Z',
    detail: 'M0.3 0.14 H0.7 V0.8 H0.3 Z M0.44 0.9 H0.56',
    aspect: 0.55,
  },
  laptop: {
    body: 'M0.14 0.14 H0.86 V0.7 H0.14 Z M0.04 0.74 H0.96 V0.86 H0.04 Z',
    detail: 'M0.22 0.22 H0.78 V0.62 H0.22 Z',
    aspect: 1.5,
  },
  envelope: {
    body: 'M0.04 0.18 H0.96 V0.82 H0.04 Z',
    detail:
      'M0.04 0.18 L0.5 0.56 L0.96 0.18 M0.04 0.82 L0.38 0.48 M0.96 0.82 L0.62 0.48',
    aspect: 1.5,
  },
  gauge: {
    body: 'M0.06 0.86 A0.44 0.44 0 1 1 0.94 0.86 Z',
    detail:
      'M0.5 0.86 L0.72 0.44 M0.2 0.62 L0.28 0.66 M0.8 0.62 L0.72 0.66 M0.5 0.42 V0.5',
    aspect: 1.15,
  },
  key: {
    body: 'M0.14 0.36 A0.16 0.16 0 1 0 0.14 0.64 A0.16 0.16 0 1 0 0.14 0.36 Z M0.28 0.46 H0.94 V0.54 H0.86 V0.66 H0.78 V0.54 H0.66 V0.64 H0.58 V0.54 H0.28 Z',
    aspect: 2,
  },
  lock: {
    body: 'M0.14 0.44 H0.86 V0.96 H0.14 Z',
    detail: 'M0.3 0.44 V0.28 A0.2 0.2 0 0 1 0.7 0.28 V0.44 M0.5 0.64 V0.78',
    aspect: 0.85,
  },
  timer: {
    body: 'M0.5 0.2 A0.4 0.4 0 1 0 0.5 1 A0.4 0.4 0 1 0 0.5 0.2 Z M0.4 0.02 H0.6 V0.12 H0.4 Z',
    detail: 'M0.5 0.6 V0.36 M0.5 0.6 L0.66 0.68',
    aspect: 0.9,
  },
  browser: {
    body: 'M0.04 0.1 H0.96 V0.9 H0.04 Z',
    detail:
      'M0.04 0.26 H0.96 M0.12 0.18 H0.16 M0.22 0.18 H0.26 M0.32 0.18 H0.36 M0.16 0.4 H0.84 M0.16 0.54 H0.7 M0.16 0.68 H0.6',
    aspect: 1.4,
  },
  bucket: {
    body: 'M0.08 0.14 H0.92 L0.82 0.96 H0.18 Z',
    detail: 'M0.08 0.14 Q0.5 0.26 0.92 0.14 M0.2 0.36 H0.8',
    aspect: 1,
  },
  user: {
    body: 'M0.5 0.08 A0.18 0.18 0 1 0 0.5 0.44 A0.18 0.18 0 1 0 0.5 0.08 Z M0.14 0.96 C0.14 0.66 0.3 0.52 0.5 0.52 C0.7 0.52 0.86 0.66 0.86 0.96 Z',
    aspect: 0.8,
  },

  // ── economics and general things ──
  coins: {
    body: 'M0.5 0.16 A0.36 0.12 0 1 0 0.5 0.4 A0.36 0.12 0 1 0 0.5 0.16 Z M0.14 0.34 V0.5 A0.36 0.12 0 0 0 0.86 0.5 V0.34 A0.36 0.12 0 0 1 0.14 0.34 Z M0.14 0.56 V0.72 A0.36 0.12 0 0 0 0.86 0.72 V0.56 A0.36 0.12 0 0 1 0.14 0.56 Z',
    aspect: 1.2,
  },
  cart: {
    body: 'M0.04 0.14 H0.2 L0.3 0.62 H0.86 L0.96 0.28 H0.28 L0.24 0.14 Z M0.32 0.72 A0.08 0.08 0 1 0 0.48 0.72 A0.08 0.08 0 1 0 0.32 0.72 Z M0.66 0.72 A0.08 0.08 0 1 0 0.82 0.72 A0.08 0.08 0 1 0 0.66 0.72 Z',
    aspect: 1.4,
  },
  factory: {
    body: 'M0.04 0.96 V0.5 L0.3 0.36 V0.5 L0.56 0.36 V0.5 L0.82 0.36 V0.96 Z M0.1 0.36 V0.1 H0.22 V0.36 Z',
    detail: 'M0.4 0.96 V0.78 H0.52 V0.96 M0.64 0.96 V0.78 H0.76 V0.96',
    aspect: 1.3,
  },
  chart: {
    body: 'M0.1 0.56 H0.26 V0.9 H0.1 Z M0.42 0.34 H0.58 V0.9 H0.42 Z M0.74 0.14 H0.9 V0.9 H0.74 Z',
    detail: 'M0.04 0.92 H0.96',
    aspect: 1.1,
  },
  scale: {
    body: 'M0.46 0.06 H0.54 V0.86 H0.46 Z M0.3 0.9 H0.7 V0.96 H0.3 Z M0.1 0.18 H0.9 V0.24 H0.1 Z M0.04 0.5 A0.16 0.12 0 0 0 0.36 0.5 Z M0.64 0.5 A0.16 0.12 0 0 0 0.96 0.5 Z',
    detail:
      'M0.2 0.24 L0.04 0.5 M0.2 0.24 L0.36 0.5 M0.8 0.24 L0.64 0.5 M0.8 0.24 L0.96 0.5',
    aspect: 1,
  },
  money: {
    body: 'M0.04 0.22 H0.96 V0.78 H0.04 Z',
    detail:
      'M0.5 0.36 A0.12 0.14 0 1 0 0.5 0.64 A0.12 0.14 0 1 0 0.5 0.36 Z M0.14 0.34 H0.18 M0.82 0.66 H0.86',
    aspect: 1.6,
  },
  building: {
    body: 'M0.14 0.98 V0.08 H0.72 V0.98 Z M0.72 0.98 V0.36 H0.9 V0.98 Z',
    detail:
      'M0.26 0.22 H0.34 M0.44 0.22 H0.52 M0.26 0.38 H0.34 M0.44 0.38 H0.52 M0.26 0.54 H0.34 M0.44 0.54 H0.52 M0.36 0.98 V0.8 H0.5 V0.98',
    aspect: 0.9,
  },
};

/** Every drawing the stage can show: the first hand-made ones, and each field's pack. */
export const PRESETS: Record<string, Preset> = {
  ...HAND,
  ...Object.assign({}, ...Object.values(PACKS)),
};

export const PRESET_NAMES = Object.keys(PRESETS);

/** Where a named part of a drawing sits inside its box, or nothing when it has none. */
export function presetAnchor(
  name: string | undefined,
  part: string,
): [number, number] | null {
  const parts = name ? PRESETS[name]?.parts : undefined;
  if (!parts) return null;
  const want = part.trim().toLowerCase();
  const found =
    parts[want] ??
    Object.entries(parts).find(
      ([key]) => key.includes(want) || want.includes(key),
    )?.[1];
  return found ? found.at : null;
}
