/**
 * Every drawing the stage can show, turned into one vector, once and
 * offline: the drawing's name and the words it is filed under, embedded
 * and written out beside the tag catalogue. The search for a drawing is
 * spelling first and meaning second, and meaning has to come from
 * somewhere; doing it here means nothing is embedded while a page is
 * being made and nothing is paid for twice.
 *
 *   npx ts-node --transpile-only -r tsconfig-paths/register scripts/visual-embed.ts
 */
import { writeFileSync } from 'node:fs';
import { config } from 'dotenv';
import { PRESET_INFO } from '../src/business/domain/visual-presets';
import { ICON_TAGS } from '../src/business/domain/visual-icons.generated';
import {
  DRAWING_DIMS,
  packVector,
} from '../src/business/domain/visual-vectors';

config();

const KEY = process.env.OPENAI_API_KEY;
if (!KEY) {
  console.error('OPENAI_API_KEY is not set; nothing embedded.');
  process.exit(1);
}
const MODEL =
  process.env.AI_EMBED_MODEL?.split(':').pop() ?? 'text-embedding-3-small';

/** The line that stands for a drawing: what it is called, then the words it is filed under. */
function lineFor(name: string, tags: string): string {
  const said = name.split('-').join(' ');
  const words = [
    ...new Set(
      tags
        .toLowerCase()
        .split(/[\s&,]+/)
        .filter(Boolean),
    ),
  ]
    .filter((w) => w !== said)
    .join(', ');
  return words ? `${said}. ${words}` : said;
}

const names = [
  ...new Set([...Object.keys(PRESET_INFO), ...Object.keys(ICON_TAGS)]),
].sort();
const lines = names.map((name) =>
  lineFor(name, PRESET_INFO[name]?.tags ?? ICON_TAGS[name] ?? ''),
);
console.log(`${names.length} drawings to embed at ${DRAWING_DIMS} dimensions.`);

/** A batch of texts as vectors, from the provider, the key never leaving the environment. */
async function embed(texts: string[]): Promise<number[][]> {
  const response = await fetch('https://api.openai.com/v1/embeddings', {
    method: 'POST',
    headers: {
      'content-type': 'application/json',
      authorization: `Bearer ${KEY}`,
    },
    body: JSON.stringify({
      model: MODEL,
      input: texts,
      dimensions: DRAWING_DIMS,
    }),
  });
  if (!response.ok)
    throw new Error(`embeddings ${response.status}: ${await response.text()}`);
  const body = (await response.json()) as {
    data: { index: number; embedding: number[] }[];
  };
  const out: number[][] = [];
  for (const row of body.data) out[row.index] = row.embedding;
  return out;
}

void (async () => {
  const packed: Buffer[] = [];
  const BATCH = 256;
  for (let i = 0; i < lines.length; i += BATCH) {
    const vectors = await embed(lines.slice(i, i + BATCH));
    for (const vector of vectors) packed.push(packVector(vector));
    console.log(`  ${Math.min(i + BATCH, lines.length)} / ${lines.length}`);
  }
  const blob = Buffer.concat(packed).toString('base64');
  const out = [
    '// Generated by scripts/visual-embed.ts. Do not edit.',
    '/** Every drawing as one vector, so a thing can be found by meaning and not only by spelling. */',
    '/** The model that made these. Vectors from two models cannot be compared, so the app checks this before it searches. */',
    `export const DRAWING_MODEL = '${MODEL}';`,
    `export const DRAWING_VECTOR_DIMS = ${DRAWING_DIMS};`,
    `export const DRAWING_NAMES: readonly string[] = ${JSON.stringify(names)};`,
    '/** The vectors, one signed byte a dimension, in the order of the names above. */',
    `export const DRAWING_VECTORS = '${blob}';`,
    '',
  ].join('\n');
  writeFileSync('src/business/domain/visual-vectors.generated.ts', out);
  console.log(
    `wrote src/business/domain/visual-vectors.generated.ts (${Math.round(out.length / 1024)} KB)`,
  );
})();
